### PR TITLE
Outdatedphp

### PR DESCRIPTION
**Pull request by jospoortvliet**
Fixes https://github.com/nextcloud/nextcloud.com/issues/686

screenshot-2017-12-11 outdated-php-5 4-5 5 nextcloud

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@jospoortvliet Is this somewhere available? Maybe in the staging area?

**Comment by jospoortvliet** [comment]
DONE: https://nextcloud.com/outdated-php-5-4-5-5/?staging=true

**Comment by jospoortvliet** [comment]
live in 30 min.

**Comment by MorrisJobke** [comment]
> live in 30 min (just needs caches to expire)

Perfect :) Thank you - will look into getting this to the users :)

**Pull request merged**
