### PR TITLE
healthcare page with our HIPAA statement

### PR DESCRIPTION
**Pull request by jospoortvliet**
Customer asked for our HIPAA statement to be on our website so I created a page for health care and added it on the bottom. Review for spelling/grammar/design please ;-)

Has already been checked on content by @oparoz 

Signed-off-by: Jos Poortvliet <jospoortvliet@gmail.com>

https://nextcloud.com/healthcare?staging=true

healthcare

### CODE REVIEW

**Comment by jospoortvliet** [comment]
As you'd see on staging, they gray-instead-of-white in the screenshot isn't actually on the page...

**Comment by MariusBluem** [comment]
See my commit above ;)

**Comment by jospoortvliet** [comment]
@MariusBluem thanks! Any more changes? If not, approve pls ;-)

**Comment by splitt3r** [comment]
@jospoortvliet the email address is info@enextcloud.com

**Comment by splitt3r** [comment]
@jospoortvliet Grey looks strange here and the link is not visible for me:

link

hover

**Comment by vaneslie** [comment]
Hey, I found two minor typos. Not sure if it has been corrected yet?!

healthcare

**Comment by MariusBluem** [comment]
> Hey, I found two minor typos. Not sure if it has been corrected yet?!

Thanks for reporting. See: https://github.com/nextcloud/nextcloud.com/pull/719

**Comment by splitt3r** [comment]
Can you also fix https://github.com/nextcloud/nextcloud.com/pull/713#issuecomment-353651010 along?

**Comment by MariusBluem** [comment]
> Can you also fix #713 (comment) along?

I think this is going to be fixed with https://github.com/nextcloud/nextcloud.com/pull/717 :wink:

**Comment by splitt3r** [comment]
Ok but one of you should fix the missing href attribute 😁

**Comment by MariusBluem** [comment]
> Ok but one of you should fix the missing href attribute :grin:

Are you able to do? If yes - be my guest and open a PR :wink:

**Comment by jospoortvliet** [comment]
Aargh had some trouble getting the changes from the PR's fixing these issues deployed but - finally done now. Waiting for caches to expire 😄 Thanks!!!

**Comment by splitt3r** [comment]
Only a question but shouldn´t external links be `target="_blank"` and `rel="noopener"` so the people stay on nextcloud.com to read further?

**Comment by jospoortvliet** [comment]
Yes, I try to do it that way. Sometimes I fail - those failures can be addressed with a PR, though 🗡

**Pull request merged**
