### PR TITLE
[RFC] fix image issues on homepage

### PR DESCRIPTION
**Pull request by Espina2**
Fix issues with image on homepage.

### CODE REVIEW

**Comment by jospoortvliet** [comment]
I think it would be good to make the image wider, I already have some empty space on the right on a full screen window and it could be worse on wider windows.

**Comment by Espina2** [comment]
You still see that with this commit? @jospoortvliet

**Comment by jospoortvliet** [comment]
yes

**Comment by Espina2** [comment]
2560 widther screenshot above, can you show me what happens in your. We should fix that, and it should be easy. :)

screen shot 2017-06-18 at 17 58 00

**Comment by jospoortvliet** [comment]
Ha, it might have been a caching issue as it doesn't happen anymore. So - solved?

**Pull request merged**
