### PR TITLE
add 7 new providers

### PR DESCRIPTION
**Pull request by jospoortvliet**
Some don't yet have a logo of us and link back to us on their site but I mailed them so I think it'll come and if not, I remove them again...

I have trouble with the providers page not working offline but that's not a problem on our server, just for when I try to add providers while in a plane from India to Abu Dhabi 😄 

Tested locally, have deployed on staging for more checking. https://nextcloud.com/providers?staging=true

Signed-off-by: Jos Poortvliet <jospoortvliet@gmail.com>

### CODE REVIEW

**Comment by MariusBluem** [comment]
Providers don’t get merged and deployed if they do not meet our requirements (yet) ... I’d propose to add those fulfilling our requirements 100% **now** and the others **later** 😉

**Comment by jospoortvliet** [comment]
fair enough. Let's give it a few days before we remove those not OK yet.

**Comment by jospoortvliet** [comment]
Checked:
- [x] https://digitalcarnage.webhop.me/index.php/login (on the bottom link to Nc... Considering their page I'm good with it)
- [x] https://www.kloecker.ac/dienstleistungsverzeichnis/n/nextcloud.php - fine
- [x] Linuxfabrik - https://www.linuxfabrik.ch/ueber-uns. Fine, fine.
- [x] https://serverdiscounter.com/drive/ - very Nextcloud branded ;-)
- [x] https://www.next-cloud.si/ / webicom - OK
- [x] https://www.operweb.com/nextcloud/ - nice Nc logos ;-)
- [ ] https://yourcloud.asia/features.php - nice comparison. They are putting logo & link live, just takes some time.

**Comment by jospoortvliet** [comment]
Checked:
- [x] https://digitalcarnage.webhop.me/index.php/login (on the bottom link to Nc... Considering their page I'm good with it)
- [x] https://www.kloecker.ac/dienstleistungsverzeichnis/n/nextcloud.php - fine
- [x] Linuxfabrik - https://www.linuxfabrik.ch/ueber-uns. Fine, fine.
- [x] https://serverdiscounter.com/drive/ - very Nextcloud branded ;-)
- [x] https://www.next-cloud.si/ / webicom - OK
- [x] https://www.operweb.com/nextcloud/ - nice Nc logos ;-)
- [ ] https://yourcloud.asia/features.php - nice comparison. They are putting logo & link live, just takes some time.

**Comment by jospoortvliet** [comment]
https://yourcloud.asia/about.php now has a logo and link. Let's get this live :rocket:

**Pull request merged**
