### PR TITLE
new collabora image needs a different main url

### PR DESCRIPTION
**Pull request by devz3r0**
Line: 157:
ProxyPass /lool/ws wss://127.0.0.1:9980/lool/ws

ProxyPassMatch "/lool/(.*)/ws$" wss://127.0.0.1:9980/lool/$1/ws

as in post:
https://help.nextcloud.com/t/updated-collabora-now-unable-to-open-documents/4179/15

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Thanks for your contribution! Really, super helpful, no way I can keep an eye on anything. YOU ROCK!

**Comment by devz3r0** [comment]
uhm @jospoortvliet  why is now the formatting at the webpage screwed up? I just changes some characters?

**Comment by jospoortvliet** [comment]
It does look good, did I miss something?

**Comment by devz3r0** [comment]
no, now its fine again, I think that was a different issue.

**Pull request merged**
