### PR TITLE
Load only the fonts we actually need, Open Sans Light & Semibold

### PR DESCRIPTION
**Pull request by jancborchardt**
Question is if we actually do need 300i, 400, 400i, 600i – @Espina2 @jospoortvliet?

Please review @nextcloud/website

### CODE REVIEW

**Comment by jospoortvliet** [comment]
I can't judge if we use the other fonts but I doubt it, I never use a 'special' font anywhere. But I'd like to hear from @Espina2 - if he also doesn't know any instances we should merge this, it's a nice improvement!

**Comment by Espina2** [comment]
@jancborchardt We use also regular. @jospoortvliet Did you not use italics on a page the have quotes from customers?

**Comment by jospoortvliet** [comment]
@Espina2 ah you mean this page: https://nextcloud.com/migration
No, the quotes use bold.  But this page uses italics in the quote from NCC Group: https://nextcloud.com/secure/

**Comment by jancborchardt** [comment]
Alright then this should work. I left in Regular as well as italic for all of Light, Regular and Semibold.

**Pull request merged**
