### PR TITLE
[WIP] New box page

### PR DESCRIPTION
**Pull request by Espina2**

### CODE REVIEW

**Comment by Espina2** [comment]
Finished layout in desktop. Can anyone start review this? @nextcloud/designers @jospoortvliet @LukasReschke

**Comment by Espina2** [comment]
Some buttons are with dummy links, maybe @LukasReschke can finish the php stuff.

**Comment by jospoortvliet** [comment]
It looks great!!! All links are broken, though, and why do you use <?php echo home_url('features') ?> for links when you could just link to /features ???

**Comment by Espina2** [comment]
I didn't make the php logic yet. For now its just dummy.

**Comment by jospoortvliet** [comment]
Ok, but what's the plan with the links? Not link but do something else? I'm curious ;-)

**Comment by Espina2** [comment]
The links it will work normally when the page is ready for commit. I still need this,

- Create icons for the Tecnology list

- Make images to responsive.

- Add links to buttons

- Add link to the PDF

If you can help in anything of this it would be nice.

**Comment by jospoortvliet** [comment]
lemme do the links then!

**Comment by MariusBluem** [comment]
Don't know whether this is intended but you can setup your email in git, so that your commits are "counted" to your account: https://help.github.com/articles/setting-your-email-in-git/ @Espina2

**Comment by Espina2** [comment]
@MariusBluem I already do that. For clone the repo I need to do that. Maybe some weird bug I don't know, but thanks. :)

**Comment by Espina2** [comment]
@jospoortvliet @LukasReschke can you deploy this to staging? @nextcloud/designers can you start review this?

**Comment by jospoortvliet** [comment]
Deployed on staging!
https://nextcloud.com/box/?staging=true

**Comment by jospoortvliet** [comment]
sorry, I can't manage to merge this to master, I'll create a new branch.

**Pull request closed without merging**
