### PR TITLE
Remove config.php from repo

### PR DESCRIPTION
**Pull request by vincchan**
Finish off config.php based on 2e4e044778dabc7f31f8517fdf56fed733dfaba7

@jospoortvliet what do you think? Will this be a problem for existing instances as it will delete those config.php too

### CODE REVIEW

**Comment by mar1u5** [comment]
Makes sense, since the 5. step of the setup-instructions for test environments is:

> Copy over config.php.sample to config.php and adjust settings as necessary (defaults will work just fine for local environments)

However ... If we remove **config.php** completely, we could also remove the line from **.gitignore**

cc @jospoortvliet

**Comment by vincchan** [comment]
@mar1u5 No, .gitignore is fine because if there was is not that entry, it will simply be committed again.

**Comment by mikebabb** [comment]
Agreed; if it's deleted and removed from gitignore as well it'll end up back in the repo as a new file when a new developer begins work on the site. I forgot to include file deletion in the commit that added the gitignore entry.

**Comment by mar1u5** [comment]
Done :wink:

**Pull request merged**
