### PR TITLE
Replace VMWelcome.png

### PR DESCRIPTION
**Pull request by enoch85**
As the title says

### CODE REVIEW

**Comment by enoch85** [comment]
cc @jospoortvliet @tflidd

**Comment by jospoortvliet** [comment]
This makes it twice as big - any chance you can run the image through https://tinypng.com first?

**Comment by enoch85** [comment]
@jospoortvliet Sure, will do!

**Comment by enoch85** [comment]
@jospoortvliet Now it's even smaller than the original ;)

**Comment by enoch85** [comment]
@jospoortvliet The picture is now gone, and removed from assets it seems. What happened?

screenshot from 2018-10-27 10 33 44

https://github.com/nextcloud/nextcloud.com/blob/master/assets/img/features/VMwelcome.png

**Pull request merged**
