### PR TITLE
Feature/noid/improve install modals

### PR DESCRIPTION
**Pull request by ma12-co**
- Make modals scrollable;
- Make navigation sticky;
- Improve spacing;

Peek 2020-10-25 09-01

### CODE REVIEW

**Comment by jospoortvliet** [comment]
This includes the changes from #1378 correct? Perhaps we could separate it?

**Comment by ma12-co** [comment]
Nope, the changes to the install page are in the other pr!

**Comment by jospoortvliet** [comment]
Hum, but if I look in 'files changed', it does show changes to the install page, and the same when I test it... something went wrong there ;-)

**Comment by ma12-co** [comment]
You're right, it's based on that branch! Should I separate it so it can be merged? Or wait for the other and rebase?

**Comment by jospoortvliet** [comment]
> You're right, it's based on that branch! Should I separate it so it can be merged? Or wait for the other and rebase?

wait for other and rebase, we should merge the other one now... If you can apply my proposed edits, I think it's good to go?!?

**Comment by ma12-co** [comment]
@jospoortvliet I dropped all other commits, now this only affect the modals so it's we can merge without waiting for the install page pr

**Review by jospoortvliet — APPROVED** [review]

**Pull request merged**
