### PR TITLE
Ep branding

### PR DESCRIPTION
**Pull request by jospoortvliet**
Added branding and remote install support.
screenshot_20161022_102119

### CODE REVIEW

**Comment by MariusBluem** [comment]
Nice 👍

**Comment by oparoz** [comment]
Could you add "Maintenance life cycle" at the top? It would partially solve the problem where we can't properly see the differences between plans.

**Comment by jospoortvliet** [comment]
@oparoz done.

**Comment by jospoortvliet** [comment]
spectacle x23340

**Comment by oparoz** [comment]
:+1:

**Comment by karlitschek** [comment]
👍

**Pull request merged**
