### PR TITLE
Remove myself from company website

### PR DESCRIPTION
**Pull request by georgehrke**

### CODE REVIEW

**Comment by georgehrke** [comment]
@jospoortvliet

**Comment by LukasReschke** [comment]
@jospoortvliet ping ;-)

**Comment by LukasReschke** [comment]
Georg waited long enough here and expressed the intent to be removed. Merging.

**Comment by Spartachetto** [comment]
@georgehrke as I use daily Nextcloud calendar and as a user that asked for features that you realized, I just want to say thank you and good luck...

**Comment by jospoortvliet** [comment]
pfff, ping me on chat pls, I have so many unread github things I don't really manage to follow it anymore...

**Pull request merged**
