### PR TITLE
[WIP] Features

### PR DESCRIPTION
**Pull request by Espina2**
TODO:
- [ ] fine-tune the new pages
- [x] add section on app store
- [x]  Add image on hero section
- [x] Set all image of features with the same size and style
- [x] add the monitoring section back and separate workflow from monitoring
- [x] create and link to a separate page about mobile clients
- [x] update sharing page
- [x] update workflow page
- [x] fix the client screenshot

To be done later:
- [ ] update WebRTC page (content needs to be rewritten due to new php-spreed app)
- [ ] find way to link to our whitepaper(s)
- [ ] create and link to a separate page about external storage (maybe)
- [ ]  Design icon for each category
- [ ] Add a image to the last call to action
- [ ] Add section with videos or at least promote our YouTube account

### CODE REVIEW

**Comment by jospoortvliet** [comment]
I feel like working on this a bit... Going to do some work on the images. That blue background, is that intentional? It looks a bit odd...

**Comment by MariusBluem** [comment]
I just want to add that I ❤️ the images @jospoortvliet added here 👍

**Comment by MariusBluem** [comment]
- Client is not a Nexcloud client currently 😁
- There is no SharePoint Integration AFAIK 🤔

**Comment by Espina2** [comment]
I think the illustrations are ok, but just want to point if we use them we should have all the points represented in the same way, so we will need more of them. :p 

I adjust the header picture. At some point, we should look to all the headers images and change them to a set that is similar. Similar colours, "subjects" persons, etc.

**Comment by jospoortvliet** [comment]
Agreed on the illustrations. If you think it is better to use screenshots only, that is OK too. As I can imagine it takes a lot of time to make the rest of the illustrations...

I don't mind the mix of illustrations, youtube videos and screenshots but that's just me being Jos.

About the images on top - absolutely. There is a difference between the various pages and styles...

I took all the images from Pexels, if you're looking for sources to adjust... Generally a search on the keywords of the page will show them up quickly.

**Comment by jospoortvliet** [comment]
I will now work on these:
- [ ] add the monitoring section back and separate workflow from monitoring
- [ ] update workflow page
- [ ] fix the client screenshot

**Comment by jospoortvliet** [comment]
working on app store section now

**Comment by jospoortvliet** [comment]
Hi all,

I would really appreciate review, esp the attention-to-detail from @MariusBluem but also @jancborchardt @Espina2 @karlitschek 

Have put this on staging:
Updated:
https://nextcloud.com/features?staging=true
https://nextcloud.com/sharing?staging=true
https://nextcloud.com/workflow?staging=true

New:
https://nextcloud.com/monitoring?staging=true 
https://nextcloud.com/clients?staging=true 

Open questions:
- [ ] Should we replace the illustrations with screenshots on the Features page?
- [ ] Do we mention sharepoint?

**Comment by karlitschek** [comment]
@jospoortvliet of course we don't mention sharepoint.

**Comment by MariusBluem** [comment]
**For Features page (not content-wise!!):**

- [ ] Add better description (longer) for theming 😁 

bildschirmfoto 2017-02-28 um 17 17 17

- [ ] Buttons should be under the texts

bildschirmfoto 2017-02-28 um 17 17 00

- [ ] Text boxes should end where pictures start 

bildschirmfoto 2017-02-28 um 17 16 47

- [ ] Menu should never ever have so much ankers to have a second row 😢 

bildschirmfoto 2017-02-28 um 17 16 01

...what about showing 4 ankers, and after it a responsive sandwich button 🤔

**Comment by MariusBluem** [comment]
**For Features page (content-wise):**

- Introduction:

- [ ] do not link to providers page (gets to much attention on this directly in the first paragraph) 

- Security first:

- [ ] , because: - (use bullet points)

- [ ] Link to ISO27001 (you can decide between iso.org, wikipedia, bsi or tüv - wikipedia seems to be most neutral to me - they do not represent ISO itself - and are translated 💪)

- Calendar / Contacts

- [ ] Please use https://github.com/nextcloud/calendar/blob/master/screenshots/2.png because I think its a better calendar screenshot with the cool sidebar 😅 

- Secure Audio / Video Calls

- [ ] Screenshot broken

bildschirmfoto 2017-02-28 um 17 37 56

- App Store

- [ ] Please don't talk about the SQL Backend (it is not compatible with Nextcloud 11, and there were problems with community people witch had upgraded already ...)

**Comment by MariusBluem** [comment]
**Sharing-page:**

bildschirmfoto 2017-02-28 um 17 42 00

after scrolling up:

bildschirmfoto 2017-02-28 um 17 42 03

using Safari 10.1 on macOS 10.12.4

**Comment by MariusBluem** [comment]
**Monitoring**: The page is fully stuffed with screenshots. Confusing. Restless.

**Comment by MariusBluem** [comment]
**Clients**: Don't like the header, and I think many professional users will think same as me ...

**Comment by jospoortvliet** [comment]
- [x] I don't have  bullet points for security items because @Espina2 
- [] Too funny? :dagger: And I thought it was freaking brilliant... Find a better one and I'll reconsider.
- [x] the rest is done.

**Comment by jospoortvliet** [comment]
Ok, let's get this on staging again this. I FIXED EVERYTHING
(mostly)

Go test. It takes 5 min for the caching to expire!

**Comment by jospoortvliet** [comment]
Remember, I have put this on staging:
Updated:
https://nextcloud.com/features?staging=true
https://nextcloud.com/sharing?staging=true
https://nextcloud.com/workflow?staging=true

New:
https://nextcloud.com/monitoring?staging=true
https://nextcloud.com/clients?staging=true

I have to pack and get ready for SCALE now - ttyl ok?

**Comment by Espina2** [comment]
@jospoortvliet very nice work!!! The features page it so much better than the current one. 

I think we can go live with what we have, but we should when use screenshots in another features page show them like we did on the features page. 

This is the only thing I think we can actually make look better at this point. 

YOU ROCK!!!!

**Comment by jospoortvliet** [comment]
Ok, in. So yeah, we should update the other images too but - later, OK? Now going to deploy this 🚀

**Pull request merged**
