### PR TITLE
[WIP] Update Visual Design on Security Page

### PR DESCRIPTION
**Pull request by Espina2**
Done

To do 

- [x] Update typography to match all the other versions

- [x] Design Icons to Integration bullet points

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Icons are looking awesome :D

**Comment by jancborchardt** [comment]
@Espina2 can you add screenshots so it’s easy to review for @nextcloud/designers? :)

**Comment by jospoortvliet** [comment]
@jancborchardt it isn't ready yet but here is a screenshot:

secure nextcloud 24-3-2017 12-03-59

**Comment by jospoortvliet** [comment]
so... No idea if this is anywhere near what @Espina2 had in mind but I changed the authentication part a bit:
secure nextcloud 24-3-2017 12-22-58
What do you think?

**Comment by Bugsbane** [comment]
Could you put the icons in their own columns, to make the layout visually more readable? eg:

image

**Comment by Espina2** [comment]
This is not finished yet @Bugsbane . But I will consider what you said when I come back to this.

**Comment by jancborchardt** [comment]
@Espina2 what do you think about centering these icons as well as their corresponding headers? That would fit with what we do on the main page too.

**Comment by jospoortvliet** [comment]
So I did what Bugsbane proposed, put the icons to the left, I think it looks nice...
secure nextcloud 16-5-2017 15-42-03

**Comment by jospoortvliet** [comment]
Made another series of changes, deployed on staging:
https://nextcloud.com/secure/?staging=true

Feedback welcome. I really want to finish and deploy this tomorrow so dear @Espina2 can focus on the install page ;-)

**Comment by jospoortvliet** [comment]
secure nextcloud 16-5-2017 23-05-52

**Comment by jospoortvliet** [comment]
So I did what Jan proposed, center the images and text. And I justified the normal paragraphs. I think this looks way better, what do others think?

secure nextcloud 17-5-2017 11-11-15

**Comment by jospoortvliet** [comment]
BTW I improved the positioning of the images on mobile. NOw again on staging:
nextcloud.com/secure?staging=true

**Comment by jancborchardt** [comment]
Awesome, way better now with the consistent column width! Only a few details:

- [ ] the hacker one logo is a bit big and could be moved above the graph to the left instead
- [ ] again – the screenshots are much too small. No need to show the blue background, the browser interface, the nextcloud header nor the left sidebar. Right now the important part of the screenshots is never really visible.

**Comment by MariusBluem** [comment]
> again – the screenshots are much too small. No need to show the blue background, the browser interface, the nextcloud header nor the left sidebar. Right now the important part of the screenshots is never really visible.

I think we should keep at least the browser interface. I don't like the idea not showing the whole interface - maybe we can make the images larger 🙈

**Pull request merged**
