### PR TITLE
[WIP] Staging and new home page

### PR DESCRIPTION
**Pull request by LukasReschke**
=> https://nextcloud.com/?staging=true

### CODE REVIEW

**Comment by jancborchardt** [comment]
Reeeally great! Good work @Espina2 & @LukasReschke :) Some feedback:

- [ ] the background color switch of the header is too jarring. Let’s try just keeping it blue
- [ ] the interface in those screenshots / device mockups needs to be way zoomed in so it’s properly visible. Also in the mobile device it should show the actual Android app
- [ ] the text of the newsletter button on the bottom needs to be changed from the non-descriptive »Just click here« to »Join our newsletter!«
- [ ] the favicon should be white on blue instead of the current blue on white. Get it from https://github.com/nextcloud/server/tree/master/core/img

That’s the first impression anyhow, need to look closer afterwards. ;)

**Comment by Espina2** [comment]
@LukasReschke how i can have this in a developement environment?

**Comment by LukasReschke** [comment]
> @LukasReschke how i can have this in a developement environment?

Let me get you a quick step-by-step tomorrow. I suppose you use OS X? :-)

**Comment by Espina2** [comment]
#

**Comment by MariusBluem** [comment]
Closed this by mistake? @Espina2 😁

**Comment by Espina2** [comment]
@jospoortvliet Something is broken? Now only show the header.

**Comment by jospoortvliet** [comment]
Yeah, something is broken, not sure what or how to fix as it works locally...

**Comment by jospoortvliet** [comment]
working now. Sorry ;-)

**Comment by Espina2** [comment]
@jospoortvliet I updated the menu the way we discuss in the conference. I think we can do that after we merge. Anyway what you think about it?

https://zpl.io/scene/Z1W2CJX

@jancborchardt @LukasReschke @karlitschek

**Comment by jancborchardt** [comment]
@Espina2 yeah, the submenu looks awesome! :) (We only need to capitalize the first character of each entry.) Also the Box page looks like it’s coming along, good start!

**Comment by jospoortvliet** [comment]
So I created a first part of the enterprise page, but some things I can't manage:

* the header - I can't get the image to replace the blue
* bullet points in front of the items in the table

Otherwise I think it isn't too bad... But it does cost me far too much time, I spend an entire day on it and I won't have time for that again this week... Hope somebody else can put in some time in the CSS/html ;-)

**Comment by Espina2** [comment]
@jancborchardt  Yup I see it before exported. Good eyes! :)

**Comment by Espina2** [comment]
@jospoortvliet Start to looking good. :)

The Header you need to remove background color, and in the button change the background color to transparent. Should work like the image above.

image
image

I will help as soon as @LukasReschke can help me to have a develop environment or some VM that I can work on.

**Comment by jospoortvliet** [comment]
My wife figured it out. Yay for @camilasan

**Comment by jospoortvliet** [comment]
> The Header you need to remove background color, and in the button change the background color to transparent. Should work like the image above.

Sadly, I don't know how to do that as the header isn't part of the page. But my wife figured it out.

I also managed to do the checkboxes: 
spectacle c20657

**Comment by jospoortvliet** [comment]
Filling in details:
spectacle t21548

**Comment by jospoortvliet** [comment]
Current look:
enterprise page

**Comment by jospoortvliet** [comment]
On the bottom I'd like to add the legal and consulting stuff, @Espina2  - instead of features. And we need to add something about what you get as part of a subscription, like the text now under the "The Nextcloud Enterprise Subscription" header.

Can you mock something up?

Todo:

* [ ] Create a separate page with the form to buy Nextcloud. 
* [ ] find out where to add prices. Perhaps on buying form page?
* [ ] add legal and consulting notes to bottom of enterprise page
* [ ] add mouse-over effects on enterprise page
* [ ] find solution in table for stuff like SLA, life cycle
* [ ] fix look of all other pages, eg text in buttons which got changed with this new page
* [ ] fix conflicts

What todo's are missing?

**Comment by jospoortvliet** [comment]
To test:
add ```?staging=true``` behind any page.
For example:
https://nextcloud.com/?staging=true (modified page)
https://nextcloud.com/enterprise/?staging=true (modified page)
https://nextcloud.com/features/?staging=true (still as it was, just new header).

**Comment by jancborchardt** [comment]
General:
- separate »Home« link is not needed because that’s what the logo is for. This makes the navigation too crowded.
- the underline of the selected header element doesn’t line up with the hover effect
- the fade of the header on the features page from blue to white is very strange and distracting. Said it before and I’ll say it again: How about we just keep it blue? That would be in line with the app too.

Enterprise page:
- the header just vanishes
- the font is serif in a lot of places because `font-family: OpenSans` is wrong. It should not need to be specified because the font stack is already defined, but somewhere it’s overridden with `body { font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;`– that needs to be removed

Front page:
- header just vanishes here too
- the screenshot contents on the top need to be bigger to be properly visible
- the scroll element needs some kind of fade transition, at the moment it’s very janky
- the scroll element sticks to the bottom of the page:
capture du 2016-09-27 16-26-26

**Comment by Espina2** [comment]
@jancborchardt 

The Header is already changed in design like show in the zeplin. (https://scene.zeplin.io/project/57bf54c24ff046f70c9b9694/screen/57c9aa04d553cb03101e7ab5)

We should not use only the blue header because if we have blue background in another section (blue in top of blue) look like crap. In the app looks good because you only use white background. And if you stick with the blue header we will fight with everything, with the jumbotrom images, illustrations and we not be limited by that. 

I think the Header the should be visible only when you scroll up in smaller devices, because you need the space for the content.

In the carousel (features area) I already animated and show some examples like I think that it should work. (https://www.uber.com/) We need the javascript expertise for do that or more time to me play with it.

All the others think you said I think its bugs in the code. But its starting to look good. :) 

Let me know if you dont agree with something.

**Comment by jospoortvliet** [comment]
@jancborchardt I addressed some of your comments, the others are simply not specific enough. Where do you see broken fonts? I don't see it and thus I can't fix. If you can find out where bad fonts are set, that would be helpful.

The header vanishes only when your screen height is too small - it then vanishes to save space. Nice, huh?

I can't fix the scroll stuff, that's Javascript dear @LukasReschke pulled of the web. I am clueless, officially.

I leave the blue vs white to you and @Espina2 

Will try to improve the screenshot contents.

**Comment by jospoortvliet** [comment]
@jancborchardt I want to put this live tomorrow, so if you have more feedback please give it/reply to my questions.

Bugs we have/things to fix:
* [ ] weird header menu issue between 768 and 1200px
* [ ] overlap of header over text on landscape mobile
* [ ] menu/header gets too wide between 1200px and 1477 creating a horizontal scroll bar
* [ ] find a (if needed, temporary) solution for the about Nextcloud 10 section's mobile issues

Edit this item to add more urgent stuff or tick those finished.

**Comment by jancborchardt** [comment]
Ok, looks a lot nicer now!

On mobile, mainly the navigation is an issue:
- [ ] you need to scroll all the way up to get to it again which is a drag
- [ ] when it's open, you can scroll down and it will vanish. Then when you scroll up a bit it comes back and it looks very glitchy


Also cc @nextcloud/website and @nextcloud/designers for testing! :)

**Comment by jospoortvliet** [comment]
I sadly can't fix the navigation here, it's javascript and I have no clue. But @Espina2 is working on it...  I think it isn't a huge issue. I'll wait until tonight, if it is still glitchy we'll just live with it and deploy, OK with that @jancborchardt ?

**Comment by skjnldsv** [comment]
May I suggest?
- [ ] Adding a background on hover for the top right download button
- [ ] Removing the border on hover for the top right download button when the header turn white
- [ ] Removing the text cursor on the entreprise feature table (because of the tooltip, more convenient)

**Comment by Espina2** [comment]
@skjnldsv Still need to work on animations in the whole website, for now only the menu on mobile have the proper behavior and still need and remove some bugs. But for sure, I suggest when you make a feedback in something visual, post a print screen or something that explain better what you are talking about, its more easy to get it. :)

**Comment by LukasReschke** [comment]
Deployed to https://nextcloud.com/?staging=true. 

- [ ] Header on older pages are broken (e.g. https://nextcloud.com/features/?staging=true)
- [ ] Animated slider on home page looks odd with lower resolutions. (https://cloud.githubusercontent.com/assets/878997/19051757/6d331fec-89b4-11e6-96bc-c83de44c2869.png)

I'll look into this.

**Comment by Espina2** [comment]
@LukasReschke Fixed Why Nextcloud on homepage. Tomorrow if you need help just say something in skype. 

Some things I need to cover 

- [ ] Replace the icon on Hamburguer menu for the design one and animate them
- [ ] Improve circle animation when tap on the button (current its not a circle)
- [ ] Create a global animation for content fade in when scroll down. 
- [ ] Buttons shouldn't have a fixed width and need to create the desire behaviour for all pages

**Comment by jancborchardt** [comment]
- [ ] The header on the front page just vanishes which is weird. I get that it should be gone for mobile, but on desktop when you scrolled down the page, you want to go to the other places of the website. And then the header has to be there. This is a usability nightmare otherwise if you have to scroll up always as if we don’t want them to use the navigation. ;)
- [ ] Same for the menu on mobile. It’s a pain to always need to scroll up again. The menu circle+icon could just hover on the top right always.

Otherwise real nice! And much better with the larger screenshots.

**Comment by jancborchardt** [comment]
@karlitschek your review would also be good. :)

**Comment by Espina2** [comment]
I agree with you @jancborchardt just need to do some things in javascript for when you scroll up they show the actual menu fixed. (This for smaller screens I think its better this way because we gain more space) 

The second part I dont get it. Can you explain better?

**Comment by jancborchardt** [comment]
@Espina2 cool, ok. If that JS is in place then the second part is also fixed, because it also concerns the visibility of the navigation. :)

**Comment by Espina2** [comment]
@jancborchardt Now the Header show when scroll up in a smaller resolutions. Have a bug that I cant figure it out that is when you are on top and scroll down, it shows the white header for after a while it goes up. 

I still want to improve the animation now its a bit weird, but it works.

**Comment by Espina2** [comment]
@LukasReschke can you help me with icon animation and the bodymovin plugin in the mobile menu?

**Comment by LukasReschke** [comment]
> @LukasReschke can you help me with the icon animation and the bodymovin plugin in the mobile menu?

Sure. Let me try to find my Skype credentials 🙈

**Comment by jancborchardt** [comment]
@Espina2 still seems to be the same here. Also, does it only appear back on smaller resolutions? Should also happen on desktop resolutions.

Additionally this is how it looks like in Firefox right now:
capture du 2016-10-05 00-27-48

**Comment by Espina2** [comment]
I think lukas not merged yet but working here. Anyway this bug on firefox doesnt show im my version of firefox... Weird. Its in all pares?

**Comment by skjnldsv** [comment]
Not here too.

**Comment by Espina2** [comment]
@jancborchardt I record some video to you see the actual version.

https://mega.nz/#!jtwDQDSC!4o90r9O7qk8ya0BEe8Ej-ZBU4d5f_6sEcLEysWMrQ10

**Comment by LukasReschke** [comment]
Newest version deployed on nextcloud.com

**Comment by LukasReschke** [comment]
- [ ] Mobile menu links have  wrong colors

**Comment by LukasReschke** [comment]
> Additionally this is how it looks like in Firefox right now:

@jancborchardt Logout on nextcloud.com, that's Wordpress injecting custom code. Also, for security reasons it would be nice to stay logged-out 🙈

**Comment by skjnldsv** [comment]
- [ ] Mobile menu has the download arrow misplaced [(screen)](https://cloud.githubusercontent.com/assets/14975046/19121355/77e75462-8b26-11e6-9901-a7bf00022bd0.png)
- [ ] Hamburger menu icon is not here [(screen)](https://cloud.githubusercontent.com/assets/14975046/19121355/77e75462-8b26-11e6-9901-a7bf00022bd0.png)
- [ ] Scrolled header still showing on mobile view 
[(screen)](https://cloud.githubusercontent.com/assets/14975046/19121421/b2540fdc-8b26-11e6-94e5-b90901d13763.png)

**Comment by Espina2** [comment]
@skjnldsv Thanks and nice feedback. 👍  

You should see the scrolled header in mobile when you scroll down, in your print screen it shows after you make scroll down?

**Comment by LukasReschke** [comment]
>  Hamburger menu icon is not here (screen)

Test again. Just pushed some code for that :)

**Comment by skjnldsv** [comment]
@Espina2 Yes, I scrolled down like 30px. 
@LukasReschke I think we should add a third line on the menu. This looks odd. If you want to keep the animation, just make the middle one fade out (see http://codepen.io/skjnldsv/pen/mPNVKJ)

**Comment by Espina2** [comment]
@skjnldsv most of the complex animations are not css, its generated in after effects and after compiled with javascript plugin. This give me more freedom to do what I want. 

> I think we should add a third line on the menu. This looks odd.

Its looks pretty nice to me, and its done the same way in design. We should not change things after that phase.

**Comment by skjnldsv** [comment]
@Espina2 I'm more a css guy for the animations, but it works great too! ;)

**Comment by LukasReschke** [comment]
> Ps: I may have some time to help. How can I set my environment for this pr? With what are you guys working?

Nice! Setting up the environment is a tad annoying but once done not that horrible. Basically you need to install a Wordpress somewhere 🙈 and then store the repo as theme: https://github.com/nextcloud/nextcloud.com#setup-of-a-local-development-environment

Then you need basically enable the theme and additionally create some pages like "enterprise" and "homepage" and then you can open /wordpress/homepage or /wordpress/buy.

Note that we're using SCSS for the CSS. The relevant stuff can be found in `/assets/css/`. Any help welcome and appreciated. :)

**Comment by skjnldsv** [comment]
@LukasReschke and how are you generating the css from the scss? I need to know so I can edit it too without changing everything :)

**Comment by LukasReschke** [comment]
> @LukasReschke and how are you generating the css from the scss? I need to know so I can edit it too without changing everything :)

[Install Saas](http://sass-lang.com/install) and then run the following:

```
sass --watch assets/css/:assets/css/
```

Then just change the SCSS files and the CSS will be regenerated.

**Comment by skjnldsv** [comment]
@Espina2 
> Its looks pretty nice to me, and its done the same way in design. We should not change things after that phase.

Well, it feels weird for me 😝 
The common way for a menu is 3 lines (or dots, see android material guidelines) 

@LukasReschke thanks! I'm having fun now! 
:stuck_out_tongue_winking_eye:

**Comment by LukasReschke** [comment]
> @LukasReschke thanks! I'm having fun now! 

Btw. please don't do any too dangerous changes right now. I'm trying to get this done into a kinda mergable state to push it live already (otherwise this is going to take a ton of time before we get to merge anything)

Once merged I'll open another staging branch from that we can incremental improve later as well :)

**Comment by skjnldsv** [comment]
I only did few small edits. Do you want me to stop for now?

**Comment by LukasReschke** [comment]
No worries that's fine. :) – Small edits work great! :)

**Comment by LukasReschke** [comment]
Ok. Merging this and pushing live soon.

**Comment by LukasReschke** [comment]
Let's iterate in other pull requests. Thanks folks!

**Comment by LukasReschke** [comment]
And this is already live at https://nextcloud.com/ 🚀 💃 🎉 🍻 🐘 🦄 

Thanks to all of you, and special thanks to the most awesome @Espina2! 🚀

**Comment by skjnldsv** [comment]
Yeeepee!

**Comment by tcitworld** [comment]
Page doesn't have a title. :(

**Comment by skjnldsv** [comment]
A man needs a name!

**Comment by jancborchardt** [comment]
Great work! :) Especially thanks to @Espina2, and @LukasReschke and @jospoortvliet  :)

(And yeah, the pages need titles again ;) in the style of `Pagename – Nextcloud`)

**Comment by LukasReschke** [comment]
> (And yeah, the pages need titles again ;) in the style of Pagename – Nextcloud)

Pull request welcome, or well, file an issue 😉 🙈

**Comment by LukasReschke** [comment]
=> https://github.com/nextcloud/nextcloud.com/issues/163

**Pull request merged**
