### PR TITLE
Remove indent from job description lists, fix code indentation

### PR DESCRIPTION
**Pull request by ViRPo**
- remove indent from lists inside job descriptions
- fix indentation in SCSS files
- trim trailing whitespace

I removed indent as @Espina2 suggested in issue #418 
I agree that bullet point's wouldn't look pretty, but I would consider visually separating job name from job description somehow (for example different font weight or adding a line to separate them)

### CODE REVIEW

**Comment by Espina2** [comment]
@ViRPo Please can you post a printscreen so we can see the result. Thanks

**Comment by jospoortvliet** [comment]
Hehe, there should be no difference ;-)

It is a nice cleanup. Sorry that much of our CSS an html is such a mess, I'm not very good at working in a consistent way :sob:

**Comment by ViRPo** [comment]
@Espina2 sure, here you go: nextcloud-job-lists

@jospoortvliet Have you tried using CSS linters? So you don't have to worry about clean code, your editor can do that for you

**Comment by Espina2** [comment]
@ViRPo 
Like you said the titles need some emphasis, maybe the class section--paragraph__tittle can make the work here. :)

We do not use linters, but if can configure one I think it should be a good addition.

**Comment by ViRPo** [comment]
@Espina2 that class works perfectly, should I just add it to all paragraph titles in job descriptions?

**Comment by jospoortvliet** [comment]
@ViRPo I'd say yes on that :+1:

**Comment by ViRPo** [comment]
@jospoortvliet so I did just that, feel free to check it out

**Comment by jospoortvliet** [comment]
Tested, great! let's merge this. Thanks a lot!

**Pull request merged**
