### PR TITLE
No demo available

### PR DESCRIPTION
**Pull request by MariusBluem**
As discussed with @karlitschek 😉 

cc @jospoortvliet

### CODE REVIEW

**Comment by LukasReschke** [comment]
Situation resolved :) => https://demo.nextcloud.com/

**Comment by MariusBluem** [comment]
> Situation resolved :) => https://demo.nextcloud.com/ – though it is still finishing deploying :)

Great news @LukasReschke 👍 ... Thank you for the fast fix 💪

**Comment by LukasReschke** [comment]
All deployed. Should work properly once the Hetzner DNS have the changes propagated. dig tells me that may still take 1800 seconds until the old entry is invalidated :)

**Comment by MariusBluem** [comment]
ReChapta working now ... It tries to create a server ... then it redirects me to demo.nextcloud.com with a high portnumber - just as intended ... but the connection does not work 😢 But lets give the server some more time 😅 I will report back and test as soon as the servers are ready 👊

**Comment by MariusBluem** [comment]
Working now 👍 THX!

**Pull request closed without merging**
