### PR TITLE
Workflow updates

### PR DESCRIPTION
**Pull request by jospoortvliet**
Updated the text:
* add intro to point out what problem we are trying to solve
* link to Outlook addin as part of the solution
* link to Security page as part of why we provide a great solution

Updated style:
* use new screenshots

### CODE REVIEW

**Comment by jospoortvliet** [comment]
workflow nextcloud 5-4-2017 10-27-38
Feedback welcome! :+1:

**Comment by jospoortvliet** [comment]
@nextcloud/website

**Comment by MariusBluem** [comment]
- too much space wasted
- think about having this screenshot section (with the same screenshots as already given in the boxes above)
- think about also linking to Thunderbird FileLink extension

**Comment by jospoortvliet** [comment]
I think the Thunderbird file link extension is a bit too obscure, for now - I will at some point add it to our outlook page, though. The rest I've done and I'll merge ;-)

Thanks!

**Pull request merged**
