### PR TITLE
Re-add Links to docs

### PR DESCRIPTION
**Pull request by LEDfan**
I think this was removed since first there wasn't any documentation, but now there is?

### CODE REVIEW

**Comment by mar1u5** [comment]
:+1:

**Comment by jancborchardt** [comment]
It needs to be https://docs.nextcloud.org instead of .com ;)

**Comment by LEDfan** [comment]
@jancborchardt thanks wasn't aware of that. Fixed it. (If wanted I'll rebase later today)

**Comment by mar1u5** [comment]
Ahh... **.com** is currently not ... yeah 😁

**Comment by jospoortvliet** [comment]
So, on one hand, yes, would be good to link. But we already have 'support' there, where you can find doc links (or will be able to, I'll do a PR soon 😁). It would simply get too long, I think... So I kind'a :-1: it...

**Comment by jospoortvliet** [comment]
(I did put the docu back in the footer, coming with another PR tomorrow morning)

**Comment by jospoortvliet** [comment]
https://github.com/nextcloud/nextcloud.com/pull/31

**Comment by jospoortvliet** [comment]
Thanks for the help, sorry this one doesn't fit well ;-)

**Pull request closed without merging**
