### PR TITLE
Swaped to the same background image as server

### LINKED ISSUE #9: Make the front page prettier
So Jan had a great idea... Christoph Wurst did some nice design work using a photo Frank made and we have this new look added in this pr: https://github.com/nextcloud/server/pull/28

Nice Nextcloud blue right? Indeed, we can use this for our front page. This isn't terribly hard, an image to replace and a bit of CSS change on the button perhaps to make it a white outline. @jancborchardt also suggested to semi-bold the font.

### PR DESCRIPTION
**Pull request by vincchan**
fixes #9

### CODE REVIEW

**Comment by mar1u5** [comment]
:+1: ...THX!

**Comment by jospoortvliet** [comment]
Oh, it looks awesome:
screenshot_20160610_085630

For the button I'd say we should make the center transparent and a thicker white outline. Something like this:
screenshot_20160610_090324

I made the outline white, 5px and the font-family Open Sans Bold. Also, the background of the button transparent. What'd yah think?

**Comment by jospoortvliet** [comment]
@jancborchardt ;-)

**Comment by vincchan** [comment]
@jospoortvliet alright, do you wanna take over or shall I alter the button?

**Comment by mar1u5** [comment]
Would be nice if you can 😉 @vincchan

**Comment by vincchan** [comment]
@mar1u5 @jospoortvliet here you go. I made the border 3px as I found 5px a bit too much. Any objections?

**Comment by jospoortvliet** [comment]
It looks great, just tested. I think that making the font bold or semi-bold would be nice, too...

**Comment by jospoortvliet** [comment]
.. but if you don't like it, that's fine. Then we merge as-is and let @jancborchardt tell us what he thinks later :dancers:

**Pull request merged**
