### PR TITLE
A brand new Box page

### PR DESCRIPTION
**Pull request by jospoortvliet**
by @Espina2 - amazing work! I just made some of the links work and changed the css in 1 or 2 places to make one bug go away, otherwise - all his. And fantastic it is!

See it live on https://nextcloud.com/box/?staging=true

### CODE REVIEW

**Comment by MariusBluem** [comment]
Is this the version which is on `staging`?

**Comment by jospoortvliet** [comment]
@MariusBluem yeah, it is

**Comment by jospoortvliet** [comment]
@MariusBluem you might have to refresh just to be 100% sure, I only just deployed!

**Comment by jospoortvliet** [comment]
@MariusBluem if you like it and find no issues, :+1: and I'll just go ahead and put it live :sweat_smile:

**Comment by MariusBluem** [comment]
> @MariusBluem if you like it and find no issues, 👍 and I'll just go ahead and put it live 😅

This was the plan 😅 ...i've re-checked everything. All links are working and the animations work well. I think its time to put this live! 👍

**Comment by MariusBluem** [comment]
Awesome work @Espina2 💪

**Comment by Espina2** [comment]
@jospoortvliet 
I think this two links are not needed because its here we are pointing with our Call to actions.

**Comment by MariusBluem** [comment]
STOOOP!

**Comment by MariusBluem** [comment]
ubuntu core link is not correct!!!

**Comment by MariusBluem** [comment]
WD link and ubuntu link is just turned around 😅 Please correct this @jospoortvliet

**Comment by Espina2** [comment]
@MariusBluem I have this problem only in mobile right?

**Comment by MariusBluem** [comment]
I have it on macOS with Safari ... Investigating 🤔

**Comment by Espina2** [comment]
screen shot 2016-10-27 at 17 49 36

No error here in Safari. Can you post a screenshot and see what error gives you in your developer tools?

**Comment by MariusBluem** [comment]
I have no error in the developer tools 😁

**Comment by MariusBluem** [comment]
works now 👍

**Pull request merged**
