### PR TITLE
Bugfix for issue #3, intro text drifting to the left

### PR DESCRIPTION
**Pull request by mikebabb**
There were a few negative left margins in the CSS causing the intro text to drift off centre. This should correct it.

Also, as this is my first pull request, let me know if anything should be done differently! Thanks.

### CODE REVIEW

**Comment by mar1u5** [comment]
Thank you 👍 ...what have you changed in the .gitignore?

**Comment by mikebabb** [comment]
I added config.php as the dev environment instructions ask you to copy and rename config.php.sample anyway, and it seemed redundant to have every new developer committing config.php after doing that when they get the site set up for local development.

**Comment by mar1u5** [comment]
Mhmm... @jospoortvliet is that ok?

**Comment by jancborchardt** [comment]
Nice! Thanks a lot @mikebabb, looks good! :)

@jospoortvliet was there any particular reason this drifting to the left was in the CSS?

**Comment by jancborchardt** [comment]
Also cc @tchncs for review since they reported the issue (always @-mention the original issue reporter for review) ;)

**Comment by mikebabb** [comment]
Got it, will do in future. Thanks for your comments, @jancborchardt!

**Comment by jospoortvliet** [comment]
awesome stuff and good adding that to .gitignore. Appreciate the help, @mikebabb  :+1:

**Pull request merged**
