### PR TITLE
Add Mathias Conradt

### PR DESCRIPTION
**Pull request by MariusBluem**
- Please test! @NinaNC @mathiasconradt

Signed-off-by: Marius Blüm <marius@lineone.io>

### CODE REVIEW

**Comment by mathiasconradt** [comment]
@MariusBluem  href="https://conradt.de/ => kein https, nur http

**Comment by MariusBluem** [comment]
> @MariusBluem href="https://conradt.de/" => no https, only http, preferably with www subdomain, so: href="http://www.conradt.de/"

Any reason for not-linking to **http://** sources?

**Comment by mathiasconradt** [comment]
@MariusBluem The root domain might be used for other purposes at some point later, never know. I usually use www-subdomains for public websites. But doesn't really matter at the moment. Can leave it at that.
(Unfortunately no ssl cause it's a verrrry old free 1&1 account (from 1998) and I don't bother to switch providers).

**Comment by MariusBluem** [comment]
www is not the problem :) just about SSL/TLS

**Comment by MariusBluem** [comment]
Done.

**Comment by MariusBluem** [comment]
Please review! @jancborchardt

**Pull request merged**
