### PR TITLE
[RFC] Better Handling of dependencies and lot of cleanups and improvoments

### PR DESCRIPTION
**Pull request by Espina2**
The same as PR above but rebased
https://github.com/nextcloud/nextcloud.com/pull/531

### CODE REVIEW

**Comment by Espina2** [comment]
- Bug on the logo on normal pages

- Bug in the enterprise illustrations

- Bug on the Toggle Collapse

**Comment by MorrisJobke** [comment]
Is this already deployed in staging?

**Comment by jospoortvliet** [comment]
yes, it is there.

**Comment by jospoortvliet** [comment]
- [ ] text under video not centered https://nextcloud.com/globalscale/?staging=true - rest is good
- [ ]  firewall icon lighter than rest https://nextcloud.com/secure/?staging=true - rest is good

**Comment by Espina2** [comment]
@jospoortvliet Can you test if is more fast than the current online version?

**Comment by MorrisJobke** [comment]
> @jospoortvliet Can you test if is more fast than the current online version?

Looks so: https://www.webpagetest.org/result/170830_4V_55871416be01abe04fe51af254cb40c6/ (staging) vs https://www.webpagetest.org/result/170830_0S_d68c6fc588c0dd2be82452892b336eca/ (current)

**Comment by MorrisJobke** [comment]
> Looks so: https://www.webpagetest.org/result/170830_4V_55871416be01abe04fe51af254cb40c6/ (staging) vs https://www.webpagetest.org/result/170830_0S_d68c6fc588c0dd2be82452892b336eca/ (current)

Basically the reduction of the pattern.svg ;)

**Comment by jospoortvliet** [comment]
Seems we could still optimize the background as we're still loading a 1.5MB svg on the front page... Could easily be cut to much smaller, esp on smaller screens. See https://github.com/nextcloud/nextcloud.com/pull/557 -> that cut it to 480 KB using a png. But we can do that later...

**Comment by Espina2** [comment]
@jospoortvliet thanks for your Hard testing. Only next week I can fix what is broken.

**Comment by jospoortvliet** [comment]
Thanks for fixing those! It'd be a shame if we didn't manage to merge this...

**Comment by Espina2** [comment]
I will finish the rest of this today. :)

**Comment by jospoortvliet** [comment]
Tested these:
- [x] https://nextcloud.com/globalscale/?staging=true
- [x] https://nextcloud.com/secure/?staging=true
- [x] https://nextcloud.com/features/?staging=true
- [x] https://nextcloud.com/secure-drop/?staging=true
- [x] https://nextcloud.com/sharing/?staging=true
- [x] https://nextcloud.com/collaboraonline/?staging=true
- [x] https://nextcloud.com/outlook/?staging=true
- [x] https://nextcloud.com/enterprise/?staging=true
- [x] https://nextcloud.com/about/?staging=true
- [x] https://nextcloud.com/support/?staging=true
- [x] https://nextcloud.com/team/?staging=true
- [x] https://nextcloud.com/events/?staging=true
- [x] https://nextcloud.com/workflow/?staging=true all
- [x] https://nextcloud.com/clients/?staging=true all
- [x] https://nextcloud.com/storage/?staging=true all
- [x] https://nextcloud.com/monitoring/?staging=true all
- [x] https://nextcloud.com/webrtc/?staging=true all
- [x] https://nextcloud.com/pricing/?staging=true
- [x] https://nextcloud.com/enterprise/buy/?staging=true
- [x] https://nextcloud.com/contribute/?staging=true
- [x] https://nextcloud.com/contributors/?staging=true
- [x] https://nextcloud.com/partners/?staging=true
- [x] https://nextcloud.com/install/?staging=true
- [x] https://nextcloud.com/release-channels/?staging=true
- [x] https://nextcloud.com/conf/?staging=true

Help finding & testing more pages welcome...

**Comment by jospoortvliet** [comment]
Further tested:
- [x] https://nextcloud.com/security/?staging=true
- [x] https://nextcloud.com/security/advisories/?staging=true
- [x] https://nextcloud.com/security/threat-model/?staging=true
- [x] https://nextcloud.com/compare/?staging=true
- [x] https://nextcloud.com/enterprise/buy/?staging=true
- [x] https://nextcloud.com/trademarks/?staging=true
- [x] https://nextcloud.com/press/?staging=true
- [x] https://nextcloud.com/changelog/?staging=true
- [ ] https://nextcloud.com/box/?staging=true
- [x] https://nextcloud.com/privacy/?staging=true
- [x] https://nextcloud.com/confinfo/?staging=true
- [x] https://nextcloud.com/design/?staging=true
- [x] 
- [x] 
- [x] 
- [x]

**Comment by jospoortvliet** [comment]
- [x] 
- [x] 
- [x]

**Comment by jospoortvliet** [comment]
I now, for sure, went through ALL pages on the website.

**Comment by Espina2** [comment]
🚀 🚀 🚀 🚀

**Comment by MorrisJobke** [comment]
🚀

**Pull request merged**
