### PR TITLE
[WIP] Homepage improvements

### PR DESCRIPTION
**Pull request by Espina2**
This can be merge, I will fix the other points in another PR

- [x] Update Slideshow on desktop resolutions
- [x] Update Slideshow logic to work on mobile resolutions
- [x] Changed Newsletter section
- [x] Added Animation when carousel swiped
- [x]  Improve page migration
- [ ] Better Navigation on Mobile

Know Bugs
- [x] Indicators on mobile are gone when change from desktop to tablet resolutions.
- [x] Position on the indicators on mobile
- [x] Page break when doesn't exist slideshow.

Pages that need to include require.js
- [x] Home
- [x] Features/Secure
- [ ] Features/Outlook
- [x] Enterprise/Overview
- [x] Enterprise/Pricing
- [x] Enterprise/Get Offer
- [x] Enterprise/Migration
- [x] Get Involved/How to Contribute
- [x] Box

Need help on testing

@MariusBluem @jospoortvliet @nextcloud/designers

### CODE REVIEW

**Comment by jancborchardt** [comment]
Umm, just pointing out that this pull request is becoming very big, and should be split in several steps. Otherwise this is impossible to review.

**Comment by Espina2** [comment]
I can't slip all the things done in here because they depend each other.

**Comment by Espina2** [comment]
@LukasReschke  need your help for make this work with your build optimizations.

**Comment by jospoortvliet** [comment]
The menu on mobile still has two issues:
- the blue background doesn't go all over the screen but only the top:
screenshot_20170125_184103
- the menu does not scroll on screens that don't fit the content (eg a BlackBerry):
spectacle lh3138

We could still merge this and fix those separate of course...

**Comment by Espina2** [comment]
I will do that in another PR after this is merged.

**Comment by jospoortvliet** [comment]
let's fix the rest in master then, before we deploy.

**Pull request merged**
