### PR TITLE
Improve the order form behaviour

### PR DESCRIPTION
**Pull request by MorrisJobke**
It now also checks the values for valid content and recalculates the price to check if everything went fine.

bildschirmfoto 2017-02-14 um 16 42 04

Inline errors:

bildschirmfoto 2017-02-14 um 16 42 20

Something went wrong page (instead of the text only version before 😉 ):

bildschirmfoto 2017-02-14 um 16 41 17

All went fine page:

bildschirmfoto 2017-02-14 um 16 37 05

Regarding the last page: I show there the content of the email. It's for validation with the potential customer. Just that we can say: yep we showed you the validated data. Is this fine? @jospoortvliet @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Best to be reviewed in whitespace free diff: https://github.com/nextcloud/nextcloud.com/pull/403/files?w=1

**Comment by jospoortvliet** [comment]
Oh I didn't enter my reply before - sorry. So this looks great. I understand you double-calculate everything, makes sense I suppose. I am testing it now 🎸

**Comment by jospoortvliet** [comment]
- [x] describe difference between basic and standard in one sentence
  - Our basic subscription offers email support with a 3 day response time, Standard offers business hours phone support with a 2 day response time.
- [x] fix link to terms and conditions - yay, thanks for catching that :D
Ok, will fix some other things later on, sales wants a different Collabora calculation... Still discussing. This - it can go from my perspective, it works. I will put it on staging now for more testing if anyone wants and then it can go live.

**Comment by MorrisJobke** [comment]
Changes look good 👍

**Comment by MorrisJobke** [comment]
Feel free to merge it

**Pull request merged**
