### PR TITLE
datasheet to case study

### PR DESCRIPTION
**Pull request by jospoortvliet**
@MariusBluem try again

### CODE REVIEW

**Comment by MariusBluem** [comment]
Wait for #529 ... looks good anyway 🙈

**Comment by jospoortvliet** [comment]
why wait to merge a typo?!?!? seriously, I want to get this out and there's no reason to wait to merge to master. I will deploy as soon as the other is merged...

**Comment by MariusBluem** [comment]
One big bug introduced by me is enough for one day ... so let me be careful. 😌

**Comment by jospoortvliet** [comment]
You introduced a bug?

Anyhow, the page is now live with this and I will promote it because it is 12:00 which means we're already 30 minutes late.

**Comment by MariusBluem** [comment]
Go 12:30 - I don’t see any problem here ;)

**Comment by jospoortvliet** [comment]
I do, it is too late.

**Comment by jospoortvliet** [comment]
I want the maximum impact, otherwise what the fuck am I doing? So no, 12:30 is too late so I've pushed it all out. Better have a button with a wrong text than being too late so you get less visitors.

**Comment by MariusBluem** [comment]
Wait at least until #529 is in... this would cause security issues to your visitors 😩

**Comment by jospoortvliet** [comment]
As those security issues are already there, it makes no difference.

**Comment by MariusBluem** [comment]
Now you have done another commit and changed the PDF. What is this for?

**Comment by jospoortvliet** [comment]
We got feedback from the TU Berlin they want ownCloud 9.1 to be mentioned explicitly. As people are now downloading the old version now this should go live asap...

**Pull request merged**
