### PR TITLE
move the Home/SME server to top

### PR DESCRIPTION
**Pull request by enoch85**
It should have been like that from start, just didn't know how to fix it back then.

Please review @jospoortvliet @tflidd

### CODE REVIEW

**Comment by tflidd** [comment]
I wouldn't place my solution first. So what is our criteria for ordering, the most popular, the oldest, ....?

**Comment by enoch85** [comment]
> the most popular, the oldest, ....?

The newest are placed on top. NetcloudPi was founded before the server. Hence the change.

**Comment by jospoortvliet** [comment]
Pfff. The order was totally random, I guess I did add stuff when I became aware of it from bottom to top but I'm not sure. If anything, alphabetical naming probably makes most sense. Don't you agree?

Also, Turrix Mox is now for sale for a while already and I should move the Spreedbox down to 'no longer available'. That I can do in a separate PR.

**Comment by enoch85** [comment]
@jospoortvliet So in other words, 

1. Remove NextcloudPi
2. Merge this PR?

**Comment by jospoortvliet** [comment]
Yeah, let's go for one. NextcloudPi is super cool, but NOT a device. So it doesn't belong there. Modify your PR to remove it, pls, then I'll merge.

**Comment by enoch85** [comment]
@jospoortvliet Done. :)

**Pull request merged**
