### PR TITLE
improve install page following feedback Jan

### PR DESCRIPTION
**Pull request by jospoortvliet**
some cleanup improvements to the install page

### CODE REVIEW

**Comment by MariusBluem** [comment]
Staging?

**Comment by jospoortvliet** [comment]
put on staging, see https://nextcloud.com/install/?staging=true

**Comment by MariusBluem** [comment]
- [ ] Mention Nextcloud version number in download section in a more prominent position 
- [ ] Consider about putting the tabs down - bad on responsive devices 
- [ ] Do the Same with client download (tabs)
- [ ] Rename More info to "Details & Download options" 
- [ ] Mention Enterprise stuff directly under "Download, Devices, Providers" with a little "You need Enterprise support" / same maybe on the download page ... this may be a point to discuss 😅

What do you think? 😁 @jospoortvliet

**Comment by MariusBluem** [comment]
Also @jancborchardt as he gaves feedback to the page 😅

**Comment by jospoortvliet** [comment]
@MariusBluem so I've implemented two of your suggestions. Not clear what you meant with the 2nd and 3rd point. The enterprise stuff - I just don't want to shove it in people's face TOO much, but I've added it to some other places.

**Comment by jancborchardt** [comment]
@jospoortvliet can you post a screenshot of the current state for quicker review?

**Comment by MariusBluem** [comment]
...or put it on staging 😅

**Comment by MariusBluem** [comment]
This should explain my 2nd and 3rd point 😅 

>  Consider about putting the tabs down - bad on responsive devices

>  Do the Same with client download (tabs)

You have moved the tabs (Archive, Web-Installer, Appliance, ...) to the bottom. This looks nice, but does not really fit on responsive devices where you have to scroll now to find other options. I think nobody wants to download Nextcloud server on his iPhone ... but maybe users of Netbooks do, or a user who want to download mobile clients 😁 @jospoortvliet

**Comment by jospoortvliet** [comment]
spectacle y29408
spectacle b29408
spectacle i29408

**Comment by jospoortvliet** [comment]
@MariusBluem putting the tabs on the bottom was on request of @jancborchardt - I don't care terribly much. What I can't do is have them on the bottom on mobile and top on desktop, sadly, that just doesn't work.

So you guys decide - top or bottom.

**Comment by jospoortvliet** [comment]
I generally think this is a step forward, we should merge and perhaps do more improvements later, unless there's a big issue you see here...

Big in the sense of "worth depriving 5K visitors/day of the other improvements for" ;-)

**Comment by MariusBluem** [comment]
I'll give my 👍 ... Lets merge this 🙈

**Comment by jancborchardt** [comment]
@jospoortvliet yep, great improvements over the current state! :) Thanks a lot and we can fix anything going forward, as always

**Pull request merged**
