### PR TITLE
[WIP] New install Page

### PR DESCRIPTION
**Pull request by Espina2**
A brand new look install page.

At the moment almost the content is "dummy" and are only made the server part.

@LukasReschke don't worry I will update the downloads links with the strings defined.

@nextcloud/designers what do you think?

install page

### CODE REVIEW

**Comment by enoch85** [comment]
LGTM but maybe use the default cloud background in the header?

**Comment by jancborchardt** [comment]
@Espina2 cool! One main information architecture change I would do is making »Server« »Desktop clients« »Mobile apps« visible by default – those are the important things. Right now Zipfile, Web installer and VM have too much importance and the switcher is barely visible.

Instead it should be 3 big boxes with a screenshot or image each:
- Server: with recommended way of installing being zipfile. web installer and VM smaller as text below
- Desktop client: automatically suggest the download according to your operating system as read through JS
- Mobile apps: same thing, check OS and show the one you use most presently.

**Comment by Espina2** [comment]
@enoch85 
> LGTM but maybe use the default cloud background in the header?
This look like a bit cliche no? 

> One main information architecture change I would do is making »Server« »Desktop clients« »Mobile apps« visible by default

@jancborchardt I didn't get that.

> Instead it should be 3 big boxes with a screenshot or image each:

I don't agree at all with this approach, first because you don't explain how that files "works" you download and should do what? 

The key idea in this approach is having a guide to install and a changelog to all the options we have. 

I don't mind having default tab called "suggested" that are the clients detected by os. But anyway if you are visiting the website with a mac, what is your phone? 

The OS thing is not so easy to implement to.

Anyway this is my humble opinion.

**Comment by enoch85** [comment]
> This look like a bit cliche no?

Hmm, I think it looks structured and recognizable. We use it on the login page and once Nextcloud is installed they will recognize themselves.

**Comment by Espina2** [comment]
@enoch85 
I am not a big a fan of the login page, but we can test, if it looks better and the other people like it, why not? :)

**Comment by enoch85** [comment]
> I am not a big a fan of the login page, but we can test, if it looks better and the other people like it, why not? :)

Cool! Other than that, great job! Much cleaner imo.

**Comment by jospoortvliet** [comment]
I love the design.

Wrt the image: A bright, cloudy image might work, like
https://www.pexels.com/photo/sky-clouds-cloudy-earth-46160/
or https://www.pexels.com/photo/nature-sky-clouds-blue-53594/
Our default image is quite dark...

with regards to showing server and clients all at once - I think it could work, it would be even MORE compact, though. With the header 'server' I think we would explain that you need that first, I guess, just like now the menu does, so it would work for me I think. THe idea of using an image/screenshot, yeah, that could be nice... Or maybe a stock image of a server/laptop/phone to make it blindingly obvious what it is for?

**Comment by MariusBluem** [comment]
@jospoortvliet Why dont we take this blue from above without a cloudy image. Would like to see this as default login image in Nextcloud too. Could be also offer an easier option for theming (changing color of login-page instead of the whole image)

What do you think? @jancborchardt @juliushaertl

**Comment by jospoortvliet** [comment]
Oh, changing our login to the blue gradient Paulo made - fine with me but an entirely different conversation :sweat_smile: 

AND I LIKE CLOUD PICTURES DAMNIT :stuck_out_tongue:

**Comment by Espina2** [comment]
> Or maybe a stock image of a server/laptop/phone to make it blindingly obvious what it is for?

I prefer to draw some custom icons for each device. Good stock photos consume much time to find, and in the end, icons work better. 

If we are going to use images on this, please try to find ones that doesn't look like stock. They should have a person that have blues tones and its not to cliche.

Example of a good looking photo.
homepage-hero

**Comment by Espina2** [comment]
So I think we should vote so I can finish this PR. 

Who think is best to have all the options to download, instead of having the menu? 
And who thinks that are best to have a photo instead of the gradient and if it the case which photo do you suggest? 

Pls say below so I can count and improve the page with your feedback. Thanks

**Comment by MariusBluem** [comment]
👍 for the menu instead of listing everything. 👍 for the blue and 👎 for having a photo instead.

**Comment by enoch85** [comment]
:+1:  For having the login page photo. :+1: For showing everything instead of a menu.

**Comment by MariusBluem** [comment]
- [ ] Replace Virtual Machine with "Appliances" and link to the VM, **and** the snap (easy Installation on Ubuntu) and maybe also docker? (Repository nextcloud/docker) ...

I can help you with that 😉

**Comment by enoch85** [comment]
> Replace Virtual Machine with "Appliances" and link to the VM, and the snap (easy Installation on Ubuntu) and maybe also docker? (Repository nextcloud/docker) ...

I vote for making a separate option for each. Otherwise we're back to the menu thing.

**Comment by MariusBluem** [comment]
Agreed 😉

**Comment by Espina2** [comment]
> I vote for making a separate option for each. Otherwise we're back to the menu thing.


@enoch85 what do you mean?

**Comment by jospoortvliet** [comment]
Well well @MariusBluem and @enoch85 vote right against each other, that helps (not) :smile_cat: 

I am afraid that if you put everything on one page, you get a lot of info again. Maybe @Espina2 could try to make a mockup with it so we can judge it?

Meanwhile, keep the blue, we can decide later if we want a picture. The blue looks nice imho anyway...

**Comment by jospoortvliet** [comment]
Even better - @jancborchardt here is a mockup for you: https://owncloud.com/download/ ;-)

**Comment by MariusBluem** [comment]
> Even better - @jancborchardt here is a mockup for you: https://owncloud.com/download/ ;-)

...this is another aspect, why I'd vote for the design with a menu 😈 Its different 😜

**Comment by MariusBluem** [comment]
Early content-wise feedback:

2ad52a3a-0e3b-11e7-8f2a-b7158109443f

**Comment by Espina2** [comment]
Marius awesome stuff. We should do all the content stuff when I finish all the logic needed. :)

**Comment by enoch85** [comment]
@MariusBluem Your mockup is actually exactly what I mean. Photo or not, that's not that important. :)

**Comment by jospoortvliet** [comment]
So with regards to selection of the right client, the thing to do would be:
* create one 'clients' page (maybe)
* when the user goes to the right page (android/desktop or 'clients') pre-select/highlight the correct entry for his/her platform
* ideally that with Javascript so we don't have issues with the caching.

**Comment by Espina2** [comment]
@jospoortvliet now it detects the browser purely with javascript. It shows the default option if you are on a desktop and if you are on mobile it shows the mobile. I will do the next part after this is tested. 

It's easy to rearrange the list and put the os you are using first.

**Comment by jancborchardt** [comment]
This is way too much text for a download page. The real one important option (zipfile) is not easy to find. And the other important options (Desktop and Mobile apps) are very small navigation items too.

I was talking to @jospoortvliet that the new Clients page is actually pretty nice: https://nextcloud.com/clients/
Just reduce the text there a bit and put download buttons below the text blocks, highlighting the relevant OS. Then add a server block too. Done. Much simpler than a wall of text.

**Comment by Espina2** [comment]
Closing the PR so you can make a new page similar to the clients.

**Comment by jospoortvliet** [comment]
@jancborchardt You can't just have one download link to the zip file because that would kill Nextcloud: the majority of users is NOT looking for a zip file. Many want a VM, a docker image, a snap and so on.

We're trying to find a solution for that. You just say you don't want the problem. Well, fine, neither do I, but it is there. We have to point people to documentation, changelog and so on. And even people who visit the site with Android have to see that there are desktop clients and a server because downloading our Android client without being aware that this is a self-hosted solution is pretty pointless.

So we need a design that can deal with that, doesn't overwhelm the user. And the design by Paulo does that. The idea of just putting a server section on the clients page - great, but that server section would then simply be as big as the page Paulo is designing so that's not a solution.

Unless you have a way that works, feel free to do a mockup. Until you actually come with a constructive idea AND can prove that it actually WORKS, I'd prefer you stay out of it. No offense, but it doesn't help to say "you do too much, I just want one button" while that is simply entirely unrealistic.

**Comment by Espina2** [comment]
Just for people see, this is what I have when I close the branch. 

 https://www.useloom.com/share/f8a7d4153c60414dbcb501bf7c51f0fa

**Comment by Espina2** [comment]
I finished all the logic for show the first the client for your OS and if you are in mobile to default open the tab mobile. 

What I need to improve is: 

- [ ] Circles Animation on TOP

- [ ] Mobile and tablet version 

- [ ] Buttons are a bit to huge

What I think @jospoortvliet and @MariusBluem can do is:

- [ ]  First complete the page with information needed

- [ ]  Second get sure all the page exist

**Comment by MariusBluem** [comment]
I'll care about the content as requested @Espina2, if this is OK for you @jospoortvliet 💪

**Comment by jospoortvliet** [comment]
@MariusBluem that would be awesome! Go ahead :+1:

**Comment by eppfel** [comment]
I'm sorry I don't have a mock, but I'm with @jancborchardt and his post was very constructive, if you look at it again @jospoortvliet. And you're actually proving our point in your first sentence: 

> Nextcloud: the majority of users is NOT looking for a zip file. Many want a VM, a docker image, a snap and so on.

People search for something particular, not for an explanation. And of course there will not just be one button, but people would like to find just the __one__ button they are searching for.

This whole page looks like a "distributions / deployments" page and not a "download" page. If you know nextcloud, you probably know your way of deployment/installation and just want that link.
If you don't know nextcloud you want to know what options you have and then use the one which is the easiest to test.

Learning about VMs, Docker etc. is another step, important, yes, but that can be _after_ the downloads. It could also be a prominent internal page link #alloptions or something, which scrolls down to the second view. The one thing I learned about download pages, was that the buttons have to be in the first view 😁 

Hope this helps a bit to understand @jancborchardt and my concerns...

**Comment by Espina2** [comment]
@eppfel 

Maybe with artificial intelligence you know wich version that specific user want, but we still have to wait a bit to that. 

> People search for something particular, not for an explanation. And of course there will not just be one button, but people would like to find just the one button they are searching for.

The user doesn't know what it wants if you don't told/show him. How do you know what you want if you don't show the options? I need to understand how you can discover what people want's.

@jospoortvliet Said inclusive that many people who download nextcloud even know that they need to install it... 

> Learning about VMs, Docker etc. is another step, important, yes, but that can be after the downloads. It could also be a prominent internal page link #alloptions or something, which scrolls down to the second view. The one thing I learned about download pages, was that the buttons have to be in the first view 😁

The buttons are the most prominent thing on the page, but if you and @jancborchardt have the vision to make anything better I love to see. Design is never perfect but I have very secure of what I came for... 

You can show the example of one better download page (you don't even need to do it). So we can see and improve it!!!

**Comment by jancborchardt** [comment]
> You can show the example of one better download page 

https://owncloud.com/download/ - all on one page, easy tp see all options, quick to scroll down.

And as said above, also https://nextcloud.com/clients - the boxes simply need a few buttons each below the text like:
- for server: one main one for the main option (which I assume is zipfile, no?) and then two smaller ones for Web installer and Appliance
- for desktop: a main one for your detected OS, smaller ones for the others to show availability
- mobile: again, highlight your detected OS but also show the other (and e.g. also show small we have a community-made Windows phone app)

Why is this such crazy design feedback? It's what I would expect on a simple download page. Quick overview and then details on drill-down. Not start with details.

As said I talked to you @jospoortvliet about using the /clients page general look and you seemed to agree, so I wonder what changed now.

**Comment by enoch85** [comment]
What are the statistics, how many times per day does the zipfile get downloaded? The VM accumulates about 140-280 GB (1.7 GB) per day from my server. Then we have the Github repo which I have no clue about.

**Comment by Espina2** [comment]
Look for what happen in mobile in that example. And for me what you said is not better the what we have here. 

> Why is this such crazy design feedback? It's what I would expect on a simple download page. Quick overview and then details on drill-down. Not start with details.

Dude, the website follow the pattern that you have and image and the details on top, so the pages follow that pattern. It's about consistency... 

For example, for the server, you can have 5/6 menu entries and can be more if we add, I don't know custom packages for each distro...

So for me, its a step behind do what you suggest.

**Comment by jancborchardt** [comment]
@Espina2 ok please just ignore their incapability to make a site work on mobile, that’s a straw man argument and not what this is about. The point is that all the info is immediately there, the information architecture is good.

> Dude, the website follow the pattern that you have and image and the details on top, so the pages follow that pattern.

How so? Where is the image, like a screenshot of the server or the apps?

> For example, for the server, you can have 5/6 menu entries and can be more if we add, I don't know custom packages for each distro

Those can go in some »Additional download options« section. We are flooding people with information here otherwise. If you are on Linux, then maybe we could also show the packages directly cause we assume you are technical. But since we want to push zipfile, VM and the like then we should prioritize that.

If everything is important, nothing is. So we need to really focus and give people the best options, not all of them.

**Comment by Espina2** [comment]
@jancborchardt Any news?
I need to finish this week or I will no time finish it.

**Comment by jancborchardt** [comment]
@jospoortvliet can you push our work-in-progress we did to a branch? We could then work on refining the information architecture and things like icons or images. :)

**Comment by jospoortvliet** [comment]
I put this on staging, Jan: https://nextcloud.com/install/?staging=true

Wip of course but I will keep it up to date ;-)

**Comment by Espina2** [comment]
This will take some time since I am completely stuck with work. Maybe at this weekend, I can take another look.

**Comment by jancborchardt** [comment]
@Espina2 do you have screenshots of the current state so we can do a design review? cc @nextcloud/designers

**Comment by jospoortvliet** [comment]
@jancborchardt it is on staging - https://nextcloud.com/install?staging=true

**Comment by MariusBluem** [comment]
Staging does not work ...

**Comment by Espina2** [comment]
This is not on staging anymore. But I will need help in the content inside here.
screen shot 2017-06-21 at 12 34 08

@MariusBluem what happen for staging not working? Please hard refresh and show me your console log.

**Comment by Espina2** [comment]
@jancborchardt its not ready yet. We already design reviewed this in another time if you remember, so a hard change again it will be another person to do it. I already lost more than 60H on this page. 

Almost of things are not done yet, like:

1. Header image/Gradient 
2. The information needed on the card of downloads, now I only have (icon, Title and download button)
3. We already detect your device/os but is not used yet.
4. For now, it only works on Server Zip option, but the content is already dynamic

**Comment by MariusBluem** [comment]
> This is not on staging anymore.

> @MariusBluem what happen for staging not working? Please hard refresh and show me your console log.

Well ... what should happen? If it is not on staging, then it is not on staging :D

**Comment by Espina2** [comment]
@MariusBluem 
Staging not working is different that this is not on staging. You said that staging are not working so I want to see why, since we are testing another thing.

**Comment by Espina2** [comment]
Currently state screenshots

screen shot 2017-06-21 at 13 25 00
screen shot 2017-06-21 at 13 24 44

**Comment by MariusBluem** [comment]
THX. I think the header is too big, and we need it a bit smaller, so that the important points (Downloads) are not hidden **that** much ;)

27383960-10cf5d76-5685-11e7-8b13-ce992a0b4168

**Comment by Espina2** [comment]
@MariusBluem 
It just needs a max-width, since the width is 80% of the screen in bigger screens it will take a lot of space. I can fix that easily. Now I'm more concern if the buttons work and update the above part correctly. That kind of thing I should do later since I already need to adjust on mobile. :)

What I really need help, is in what to show in here in the screen above.
screen shot 2017-06-21 at 16 00 27

**Comment by MariusBluem** [comment]
Archive (ZIP), Web-Installer, (VM, Snap, Docker, -> may be combined to Appliances) ...
Please don’t forget Providers and a place to spot Enterpise :)

**Comment by Espina2** [comment]
Providers and devices should not be related directly to download options. We should mention then somewhere but should be not directly associated

**Comment by jancborchardt** [comment]
Awesome, that looks good! Just a few details for now:

- The buttons should be specific, not all "Get Nextcloud". Rather "Install Nextcloud server", "Download Nextcloud for desktop", "Get Nextcloud mobile apps"
- For the mobile apps, I would directly put the app store badges directly linked to the store. That's what people immediately get.
- Similar for the desktop app, we should show grey icons for the supported platforms between the text and the button.

**Comment by Espina2** [comment]
@jancborchardt I agree with all the things you said, and I already have that in mind to. Do you have any suggestions for the download buttons. It should something more smaller, "Nextcloud for mobile", "Nextcloud for desktop", but since we already have the title maybe we don't even need to repeat "server", "mobile", etc.

**Comment by jancborchardt** [comment]
Yeah, duplicating is a bit strange but the call-to-action buttons especially should always have the specific actions on them. :) We can make the text a bit shorter though, yes.

**Comment by Espina2** [comment]
@jancborchardt @jospoortvliet @MariusBluem We should discuss this.

**Comment by jancborchardt** [comment]
Here’s a dirty mockup from some months ago, not sure if you saw that. That depicts how the buttons should be, and some secondary options which shoud only be text links. For the mobile apps for example, directly show the app store buttons.

**Comment by Espina2** [comment]
@jancborchardt I discuss this page when @jospoortvliet had in Portugal, and he said to me that some things changing and even the mockup you did when we talk is outdated. 

So should we still do this or talk again about the subject?

**Comment by jancborchardt** [comment]
Then it would be good if we can have it in writing here what's outdated. :) cc @jospoortvliet 

From a flow perspective that design of course still stands.

**Comment by jospoortvliet** [comment]
Ehm, looking at the current state here:
https://github.com/nextcloud/nextcloud.com/pull/434#issuecomment-310062513
Isn't that exactly what the mockup shows?
3 items: Server/Desktop/Mobile with icons above and download button below

Of course there's a lot more complexity so when you click that download button you should get the 'default' action or a choice. There isn't always a default so often - choice...  You can show some more options at the same time as in the mockup or hide them more behind a 'get' as Paulo did - seems a detail to me.

**Comment by jancborchardt** [comment]
@jospoortvliet see my remarks on that 3 comments down, basically explaining what the mockup shows. ;)

**Comment by jospoortvliet** [comment]
And @Espina2 agreed so it looks like we're going in the right direction.
https://github.com/nextcloud/nextcloud.com/pull/434#issuecomment-311123915

Yeah, I dunno what I meant with outdated in Portugal, I guess the biggest part is - we have a lot of things we want to show. But I think what we have now will scale to that so it seems best to me to continue implementing it. The only part I'm not happy about is that without Javascript it won't work; and that I won't be able to change it as it requires javascript. Doing more/most with simpler html/css would be nice... And I'm sure it is possible. But - I leave that to Paulo, if he really prefers to do it this way, so be it.

**Comment by jancborchardt** [comment]
The only JS is really the finding out the person's operating system and moving/styling the parts appropriately, or what do you mean?

**Comment by jospoortvliet** [comment]
>The only JS is really the finding out the person's operating system and moving/styling the parts appropriately, or what do you mean?

moving and styling can be done in CSS and html, that way I can maintain it...

**Comment by Espina2** [comment]
@jospoortvliet Maybe I'm confusing something but I remember that you say something about the new client having providers embedded that the workflow can change a lot. 

I really want to know if it will or not, because doing something that will not response to the actual needs is just putting effort in something that will no work. :)

If you are saying that nothing change I can finish this.

**Comment by jospoortvliet** [comment]
@Espina2 aaah now I remember. Let's discuss this by mail ;-)

Expect one soon.

**Comment by jancborchardt** [comment]
Could you also let me know about this? Ideally just comment here …

Do you mean that we will primarily show the desktop client for download cause providers and server can be chosen in the flow there? (If so, I disagree cause then the website doesn't give people a proper mental model about what the parts of Nextcloud are.)

**Comment by jospoortvliet** [comment]
@jancborchardt no, just wait for the mail ;-)

**Comment by jancborchardt** [comment]
Whatever happened to the state shown in https://github.com/nextcloud/nextcloud.com/pull/434#issuecomment-310062513

> Currently state screenshots
> 
> screen shot 2017-06-21 at 13 25 00
> screen shot 2017-06-21 at 13 24 44
> 

Cause this looked great! @Espina2 @jospoortvliet

**Pull request closed without merging**
