### PR TITLE
[RFC] Switched Home and Bussiness Image

### PR DESCRIPTION
**Pull request by Espina2**
https://github.com/nextcloud/nextcloud.com/issues/197

Ignore this two commits in the merge  [WIP] Initial Structure [WIP] Finished the structure

### CODE REVIEW

**Comment by jospoortvliet** [comment]
I will:
* resolve the conflicts
* put a jpg image in as a 2.4 mb png on our front page is a bit extreme :scream_cat:

**Comment by jospoortvliet** [comment]
Now I see a HUGE amount of other changes, so I'll have to spend some time testing. What are the other changes supposed to do? I see some css moved around but also changed, and the header php is changed, too... Will this not cause issues with the PR about menu's in the header, for example? Be careful please with such changes!!! This can break a lot.

**Comment by jospoortvliet** [comment]
yeah, exactly
so this breaks everything ;-)
I will create a new PR with just the new images, OK?

**Comment by Espina2** [comment]
Yes do it please. I think we can merge only the commit that we want. The others changes is related with the Header PR that I am working. Thanks.

**Comment by jospoortvliet** [comment]
please merge the other one then ;-)

**Pull request closed without merging**
