### PR TITLE
Fix provider default selection

### PR DESCRIPTION
**Pull request by skjnldsv**
Thanks a lot to @TheFirstGoodmaN

### CODE REVIEW

**Comment by TheFirstGoodmaN** [comment]
@skjnldsv @jospoortvliet 
Great, i hope it helps.
Thank you two for your fast response!

**Comment by skjnldsv** [comment]
@TheFirstGoodmaN will be released automatically tonight :)
@MorrisJobke can you confirm?

**Comment by TheFirstGoodmaN** [comment]
@skjnldsv
Oh great, sorry, I was just curious, it was not my intention to stress you.

**Comment by skjnldsv** [comment]
@TheFirstGoodmaN No worries ;)
I'm already stressed by another big piece of work :p

**Comment by MorrisJobke** [comment]
> @TheFirstGoodmaN will be released automatically tonight :)
> @MorrisJobke can you confirm?

No - website is manually deployed by @jospoortvliet or anybody from the sysadmin team. But I can do it now.

**Comment by MorrisJobke** [comment]
Done.

**Comment by TheFirstGoodmaN** [comment]
@skjnldsv 
@MorrisJobke 
Thank you, it works like a charm now!
Just the cache needs to expire.
Thanks!

**Pull request merged**
