### PR TITLE
add user management page

### PR DESCRIPTION
**Pull request by jospoortvliet**
This page covers our integrated user management, LDAP, 2FA and some other backends and features.

screen shot 2017-11-23 at 18 43 50-fullpage 1

### CODE REVIEW

**Comment by NinaNC** [comment]
Hi, see my editions below. As always, propositions :)

33184774-a7a47b50-d07e-11e7-9956-7c2baf4aa83f

**Comment by jospoortvliet** [comment]
Good stuff. All integrated.

**Comment by MariusBluem** [comment]
too much whitespace:

33184774-a7a47b50-d07e-11e7-9956-7c2baf4aa83f

**Comment by MariusBluem** [comment]
@blizzz read the screenshots 😊🙈

**Comment by jospoortvliet** [comment]
Sorry - you can indeed either read the screenshot, look at the code or built the website. But there's one more option and I've got you covered: this is now on 
https://nextcloud.com/usermanagement/?staging=true

Enjoy ;-)

@MariusBluem done. Check out staging (old version might still be cached, give it 30 min if it ain't different yet)

**Comment by blizzz** [comment]
* built-in, not built in
* full-features, not full featured
* an LDAP, not a LDAP
* an SSO, not a SSO
* "SAML 2.0 is supported ~~with~~ OneLogin, Shibboleth and ADFS" → supported against I'd say. Plus, comma behind Shibboleth
* webservers → web servers
* app-specific, not app specific
* "HTTP requests can be used via a Basic Auth header to easily integrate workflows ~~in~~ existing tools and infrastructure."  → with

Cheers from grammarly.com ;)

> as well as built in account management with optional two-factor authentication and Single-sign-on support.

2FA is also possible against LDAP (e.g. on c.nc.c :p) as well as is SSO via user_saml

> A plugin infrastructure exists with applications available

In upcoming 13… and a demo app that is not on appstore and specific to the vendor :)

> Creating, updating and removing LDAP configurations can optionally be done through an external, REST-based API.
> 
>  Find documentation here.

You wanna use that link for the API: https://docs.nextcloud.com/server/12/admin_manual/configuration_user/user_auth_ldap_api.html

Fine otherwise

**Comment by jospoortvliet** [comment]
awesome, thanks, implemented. Can one of you approve & merge so I can deploy?

**Comment by jospoortvliet** [comment]
(deployed again on staging, should work soon)

**Pull request merged**
