### PR TITLE
Update page-homepage.php

### PR DESCRIPTION
**Pull request by jospoortvliet**
How about we link to this on the home page... The conf is old news ;-)

### CODE REVIEW

**Comment by jancborchardt** [comment]
We're not going to use this to announce every blog post now, right? ;)

Remember that the main claim, detail text, screenshot and call to action are the most important elements. Anything nonessential like this should be avoided.

It's fine for things like new releases and the conference, but that's it.

**Comment by jospoortvliet** [comment]
Well, this is quite a major thing for customers etc, it certainly isn't "every blogpost" as we published more than a dozen since we did this one. If you have a better idea let me know, until then I think this is a good thing to promote. What else? Marius had some ideas... This is at least something our prospective customers should read.

**Comment by jancborchardt** [comment]
Alright, your call. Agree the currently pinned tweet should be updated, maybe with the conf recap post?

**Comment by jospoortvliet** [comment]
Allright, conference report is what it links to. Now we're already weeks after the conference, can somebody PLEASE just approve SOMETHING, ANYTHING that is better than our embarrassing "join the conference August 22-27" please? If you don't like this propose something better.

**Pull request merged**
