### PR TITLE
some updates

### PR DESCRIPTION
**Pull request by jospoortvliet**
would be nice to have some design fu on this one ;-)

### CODE REVIEW

**Comment by jospoortvliet** [comment]
What it looks like now:

enterprise - nextcloud

@jancborchardt

**Comment by jospoortvliet** [comment]
<Blizzz> add 1-50 users, community support, community consulting, no commercial support, FREE

**Comment by jancborchardt** [comment]
Mostly the table could use a bit more info what differentiates the tiers. Currently it’s really only the support range. Is there nothing else? (Having the deployment and security consulting be the same doesn’t help there. ;)

Do or should we offer anything else specifically? cc @karlitschek

**Comment by jospoortvliet** [comment]
Yeah, there simply is nothing else at the moment. There are no tiers, actually, it's just that if you have more users the cost/user goes down ;-)

**Comment by blizzz** [comment]
> Yeah, there simply is nothing else at the moment. There are no tiers, actually, it's just that if you have more users the cost/user goes down ;-)

You could merge the cells and write it down only once, or have a description on the left side and work with green checkmarks and red crosses, or something like that. However, there are really few things for a comparison, making me doubtful whether it really has value or keeps people off. Maybe the wall of text can be reduced and aspects soaked in here? Another think to consider: with the additional FREE column, the central ones can be merged and discount ranges mentioned in the table.

**Comment by MorrisJobke** [comment]
And maybe change `Eur 3200` to `3200 €`

**Comment by jospoortvliet** [comment]
So we still have to figure out how/what/where to sell, let's do that before we create a webpage ;-)

Will close this PR for now.

**Pull request closed without merging**
