### PR TITLE
Increase clickable menu nav area

### LINKED ISSUE #401: Increase clickable area of header popover menu entries
Currently only the text area is clickable. It should expand to more height (no space between the links) and all the way to left and right.

cc @nextcloud/website @nextcloud/designers

### PR DESCRIPTION
**Pull request by ViRPo**
- refactor menu link spacing from margin to padding
- add display block to menu links so padding applies to them
- trim trailing space at line 14

With this PR I want to resolve #401
Do the changes look alright?
What is your standard way of compiling *.scss files? Should I use specific settings or will it be automatically done on staging? I might need a small hint about that :)

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Great job!!! Yeah, this worked, just tested it. The CSS we compile with sass and commit as part of the PR. I'll create a new PR with your code and the compiled CSS ;-)

**Comment by Espina2** [comment]
Just a suggestion if you want to increase the clickable area, its better to use padding: 0 10px; since padding-left it will only make them bigger on the left side.

**Comment by ViRPo** [comment]
@Espina2 that's a good suggestion
I will add the padding and compile SCSS later today and update this PR :)

**Comment by ViRPo** [comment]
I was trying to figure out all the *.css.map *.css.orig *.css.map.orig files and then I realized they are ignored by git and I just had to run sass :)

**Comment by jospoortvliet** [comment]
hehe, sorry about the confusion... We should update the readme, any chance you could describe what you learned there for the next person who comes along?

**Comment by ViRPo** [comment]
@jospoortvliet describe it here or in the readme? :)
I'm guessing in here, so: For every SCSS file, there should be one CSS file compiled with sass (or also node-sass on Win) without any special settings (not nested or compact) and both of these files should be up-to-date when merging them anywhere
*.css.map files are ignored by git and are there just for debugging purposes. Should you ever need them, you can use them/create new ones

After my 2nd commit, does it look alright?

**Comment by jospoortvliet** [comment]
Great work! Yeah, this rocks. I'll merge and test :eyeglasses: and then, if OK, deploy.

WRT the description of what to do - I did mean for the readme, yeah, do a PR on that if you are OK doing that ;-)

Good description, just add that!

**Comment by jospoortvliet** [comment]
Works, deployed! Thanks a lot @ViRPo  - you made our website a little better. And with already over 60K visitors this month, that matters to a lot of people...

**Comment by ViRPo** [comment]
@jospoortvliet I will gladly add that to readme
I will probably also try to fix another thing or two in this or other Nextcloud repositories, since I got a pretty cool class assignment to go explore open-source/github world and contribute a bit and I really like the idea behind Nextcloud :)

**Pull request merged**
