### PR TITLE
Fix SCSS readme note

### PR DESCRIPTION
**Pull request by ViRPo**
As it turns out, I was wrong with my notes aboud compiling SCSS
Truth is, every CSS file currently has sourceMappingURL set at the end of the file, which means, that all SCSS files were originally compiled with sourcemap option turned on.
Not compiling them together with sourcemap would mean deleting sourceMappingURL from the css file, which is unwanted

### CODE REVIEW

**Comment by jospoortvliet** [comment]
mja, I just use `sass --watch *.scss`
and `sass bla.scss bla.css` and never got in trouble but this might be more correct ;-)

**Comment by Espina2** [comment]
We just need to run sass --watch path to assets.

**Comment by ViRPo** [comment]
I see, what would you suggest to write to readme note?

**Comment by jospoortvliet** [comment]
Maybe just add to what you wrote:
During development it is useful to use the `--watch` option, running the command: `sass --watch [location to scss files]` which will instantly update the CSS files whenever you modify the scss ones.

**Comment by ViRPo** [comment]
It's a small step for a man and small step for a humanity, but I finally figured out, what the recommended settings should say
There are many recommended ways to achieve that in Windows, but `sass --watch [location]` should work just fine for most cases even in Windows :)

Sorry for the mess

**Comment by jospoortvliet** [comment]
:+1:

**Comment by jospoortvliet** [comment]
Thanks a lot! Every little bit helps - I know @NinaNC is setting up a website dev environment so this will certainly help her :D

**Comment by NinaNC** [comment]
Current state: 


alt="I'd better do this during the week-end"

**Pull request merged**
