### PR TITLE
New about

### PR DESCRIPTION
**Pull request by jospoortvliet**
## TODO:
* [x] rethink the menu perhaps?
* [x] fix the youtube thing on the about page
* [x] show the social accounts on the team page

### Contributors page
The contributors page will have the list of contributors on it like on [our current page that is live](https://nextcloud.com/contributors) - I just don't have that data locally. The contributors show above the bottom blue bar.

Note: I already made the top image a bit darker.
contributors nextcloud 8-2-2017 18-29-53
### Jobs page
nextcloud 8-2-2017 18-10-04

### Team page
team nextcloud 8-2-2017 18-09-34

What do you think @Espina2 @jancborchardt @karlitschek @MariusBluem

### CODE REVIEW

**Comment by karlitschek** [comment]
looks nice 👍

**Comment by MariusBluem** [comment]
...very nice 🙈👍

**Comment by Espina2** [comment]
Some things:

- [ ] In the Team page, its better to have a picture with faces. 

- [ ] When I made the second Navbar the purpose is to people going directly to the content they want in the page, for navigate between pages we should use the normal navigation.

**Comment by jancborchardt** [comment]
Yep, the team picture header should be faces, ideally from us really, from an event. Not crotches. ;)

But with the navigation the subnavigation could help findability. I get @Espina2's point though.

**Comment by jospoortvliet** [comment]
Right now the issue is - what picture to use on the team page? We still have no decent image of our company team. Same with the community page. I could use the conference image on all three pages but that doesn't look great and the image of our office we have isn't good enough.

Thoughts, @jancborchardt - we REALLY have to make sure to take a picture in the office, a good one. And a company group pic, too, I think. I'm still sad we didn't take a good one of the team at FOSDEM :(

**Comment by jospoortvliet** [comment]
After talk with @Espina2 decided to keep the images as they are for now.

Will fix the other points, then - review, test, merge, go 🚀

**Comment by jospoortvliet** [comment]
Many thanks to @camilasan for fixing the youtube stuff... require.js isn't as simple as it seems I guess ;-)

**Comment by jospoortvliet** [comment]
It is now on staging and all look good:
https://nextcloud.com/team/?staging=true
https://nextcloud.com/about/?staging=true
https://nextcloud.com/contributors/?staging=true
https://nextcloud.com/jobs/?staging=true (no changes)

**Comment by jospoortvliet** [comment]
deploying to live!

**Pull request merged**
