### PR TITLE
Fix several security concerns

### PR DESCRIPTION
**Pull request by LukasReschke**
This fixes several HackerOne tickets.

- Issue: The IP address could always be spoofed to bypass any ratelimit
  - Fix: Always use REMOTE_ADDR
- Issue: The captcha can be bypassed trivially as there is no real validation. (it's all client-side, the client can just claim it solved the captcha properly.)
  - Fix: Removed the captcha and replaced it with a ratelimit per IP address. One can now call `canPerformLimitedAction` and specify the amount of times an action can happen at most within an hour, as well as the action name. (if a client exceeds this limit, they are blocked for this specific action until 1 hour has passed without any action on that endpoint from them)

I have not tested this, as I have not sufficient time to setup the nextcloud.com environment including Redis locally. But the code should work. If not, revert and let me know what is broken.

Note: The rate limit exceeded pages could potentially look horrible, as I just call a `die()`. If you want it too look nice, you can probably play around this by setting `error_message` etc.

### CODE REVIEW

**Comment by jospoortvliet** [comment]
> There has been a critical error on your website.

```
[Fri Apr 16 13:57:17.951867 2021] [php7:error] [pid 22217] [client 127.0.0.1:59404] PHP Fatal error:  Uncaught Predis\\Connection\\ConnectionException: Connection refused [tcp://127.0.0.1:6379] in /home/jospoortvliet/source/nextcloud.com/vendor/predis/predis/src/Connection/AbstractConnection.php:155\nStack trace:\n#0 /home/jospoortvliet/source/nextcloud.com/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\\Connection\\AbstractConnection->onConnectionError()\n#1 /home/jospoortvliet/source/nextcloud.com/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\\Connection\\StreamConnection->createStreamSocket()\n#2 /home/jospoortvliet/source/nextcloud.com/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\\Connection\\StreamConnection->tcpStreamInitializer()\n#3 /home/jospoortvliet/source/nextcloud.com/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\\Connection\\StreamConnection->createResource()\n#4 /home/jospoortvliet/source/nextcloud.com/vendor/predis/predis/src/Connection/StreamConnection.php(258): Predis\\Connection\\AbstractConnection->connect()\n#5  in /home/jospoortvliet/source/nextcloud.com/vendor/predis/predis/src/Connection/AbstractConnection.php on line 155, referer: http://127.0.0.1/wordpress/whitepapers/
```
Looking at the ratelimiting.php file, our website now requires Redis? I don't have that set up locally so I can't test it I presume?

**Comment by LukasReschke** [comment]
> Looking at the ratelimiting.php file, our website now requires Redis? I don't have that set up locally so I can't test it I presume?

The website already required Redis before. You likely just never used locally parts of it, that did use it :) (Simple Signup etc - https://github.com/nextcloud/nextcloud.com/search?l=PHP&q=predis)

But if you prefer, for easier simple setup I can just make the code always return `true` when no Redis is deployed? :) - That would make it probs easier for all of you.

**Comment by jospoortvliet** [comment]
> The website already required Redis before. You likely just never used locally parts of it, that did use it :) (Simple Signup etc - https://github.com/nextcloud/nextcloud.com/search?l=PHP&q=predis)
> 
> But if you prefer, for easier simple setup I can just make the code always return `true` when no Redis is deployed? :) - That would make it probs easier for all of you.

I guess, yes, then at least I can test the basic functionality (if the forms send emails, if the mails look good etc). The actual rate limiting we can then test live of course.

**Comment by jospoortvliet** [comment]
# local tests
* [x] trial form http://127.0.0.1/wordpress/trial/
* [ ] whitepaper http://127.0.0.1/wordpress/whitepapers/
* [ ] sales http://127.0.0.1/wordpress/buy/
* [ ] partnerapply http://127.0.0.1/wordpress/partnerapply
* [ ] order http://127.0.0.1/wordpress/order/
* [ ] ionos http://127.0.0.1/wordpress/ionos/
* [ ] include http://127.0.0.1/wordpress/include/
* [ ] contact http://127.0.0.1/wordpress/contact/
* [ ] appmarketing http://127.0.0.1/wordpress/appmarketing/

# live tests
* [ ] trial form 
* [ ] whitepaper
* [ ] sales
* [ ] provider
* [ ] partnerapply
* [ ] order
* [ ] ionos
* [ ] include
* [ ] contact
* [ ] appmarketing

**Review by jospoortvliet — APPROVED** [review]
Tested locally, works for the forms tested. Will test live a bit more with Vanessa.

**Pull request merged**
