### PR TITLE
2018 has events, too!

### PR DESCRIPTION
**Pull request by jospoortvliet**
Anything I forgot?

Signed-off-by: Jos Poortvliet <jospoortvliet@gmail.com>

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Deployed on staging: https://nextcloud.com/events?staging=true

Anyone willing to check and approve?

**Comment by MariusBluem** [comment]
Do we want to keep 2017?

**Comment by jospoortvliet** [comment]
Yes, that way people get an idea of where we've been. I'd like to hide it behind a drop-down later this year.

**Comment by jospoortvliet** [comment]
sorry, has to go live or our article and newsletter point to an outdated page.

**Pull request merged**
