### PR TITLE
[WIP]FixBugs made by enterprise Merge

### LINKED ISSUE #346: Capitalization of call-to-action bar on Pricing & Enterprise pages
This whole bar uses all-caps:
capture du 2017-01-17 13-30-03

As talked about before, we never ever do that. It looks ugly, is not very legible, you can’t discern where one entry on the left ends and the other one begins, and it seems as if we are screaming at people.

We always only capitalize the first character of an entry or a button. cc @nextcloud/website

### LINKED ISSUE #347: Fade on top of website?
I just noticed this on the top of the website:
capture du 2017-01-17 13-31-42

It looks very strange, especially since everything else is plain color. What was the reason for adding this? cc @nextcloud/designers

### LINKED ISSUE #350: css.orig files?
Are these files like custom.css.orig and custom.scss.orig still needed, or just leftovers? They even have merge conflict traces in them, like:
```
<<<<<<< HEAD
=======

>>>>>>> 73267d428852c47c6c5a900f2041783cabe1eb01
```

Seems like we should delete them? @nextcloud/website

### PR DESCRIPTION
**Pull request by Espina2**
- [x] fixed #347
- [x] fixed #346
- [x] fixed #350

### CODE REVIEW

**Comment by jancborchardt** [comment]
Good stuff, thanks a lot! :+1:

**Comment by jancborchardt** [comment]
@Espina2 is this still work in progress?

**Comment by Espina2** [comment]
@jancborchardt we can merge it, but I want to first know if you still have the issue on the mobile menu.

**Comment by jancborchardt** [comment]
We can merge it first & deploy, and then work on this separately. Better to do separate pull requests anyway. :)

**Pull request merged**
