### PR TITLE
Bump up minimum macOS version to 10.14

### PR DESCRIPTION
**Pull request by claucambra**
Due to the client's new notification system, the minimum required version is 10.14

### CODE REVIEW

**Review by mgallien — APPROVED** [review]

**Comment by rakekniven** [comment]
Why is the website showing "10.12+" and this PR says it should be "10.13+"? 

URL: https://nextcloud.com/install/#install-clients

Screenshot 2022-05-21 at 12 22 44

**Review by rakekniven — APPROVED** [review]

**Comment by claucambra** [comment]
> Why is the website showing "10.12+" and this PR says it should be "10.13+"?
> 
> URL: https://nextcloud.com/install/#install-clients
> 
> Screenshot 2022-05-21 at 12 22 44

Seems like maybe the prior change wasn't deployed

**Comment by rakekniven** [comment]
> Seems like maybe the prior change wasn't deployed

Ok. That caused some noise in the forums as well. I was hit myself trying to install it on my 10.12 system.

**Comment by modelcode** [comment]
Not good.

**Comment by mgallien** [comment]
change done on website

**Pull request closed without merging**
