### PR TITLE
Minor fixes on Include page

### PR DESCRIPTION
**Pull request by kevgathuku**
- Fix typo (send instead of sent)
- Fix link to Camila Ayres LinkedIn profile

### CODE REVIEW

**Comment by tflidd** [comment]
Is this ok like this for your linked in profile @camilasan?

**Comment by jancborchardt** [comment]
Seems good to me! :) cc @camilasan @shironextcloud for review.

**Comment by jancborchardt** [comment]
Merging cause the previously linked Camila is definitely not @camilasan. :)

**Comment by jancborchardt** [comment]
The link was also wrong on the team page, fix at https://github.com/nextcloud/nextcloud.com/pull/1016 :)

**Pull request merged**
