### PR TITLE
Add new NextcloudPi URL

### PR DESCRIPTION
**Pull request by tflidd**
Small changes to wording, putting the new name and link of the project.

Fixes https://github.com/nextcloud/nextcloud.com/issues/864

### CODE REVIEW

**Comment by jospoortvliet** [comment]
This name change is going to change again - given that 'NextcloudPlus' sounds more like a Nextcloud fork than a disk image for development boards, I had to ask to change it. Remember the CalendarPlus and ContactsPlus apps 'back in the day', forks of the originals? :cry:

**Comment by jospoortvliet** [comment]
Oh there are more changes than the name-to-plus, sorry for missing that. I haven't seen them pick a final name, might stick with NextcloudPi - for now I guess we should keep that here...

**Comment by MariusBluem** [comment]
Nextcloud Plus is not a good name, since as @jospoortvliet mentioned it sounds like a fork. I don’t want to think about discussions like „I am running Nextcloud - well, I am even running Nextcloud Plus“ ... it sounds like the Plus makes Nextcloud better by design, which is not the case. It’s just another way of running the same code base with an very undescriptive and misleading  trademark.

**Comment by tflidd** [comment]
They decided to stay with the RaspberryPi name (https://help.nextcloud.com/t/feedback-welcome-naming-for-nextcloudpi-project/29356/8). They have a dedicated URL, I also changed the wording a bit.

**Comment by jospoortvliet** [comment]
Perfect!

**Pull request merged**
