### PR TITLE
Small link fixes

### PR DESCRIPTION
**Pull request by splitt3r**
Fixed missing links + using variables for doc links.

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Now you're being too clever. I don't know what you are doing here so I have to test it ;-) gimme some time :boom:

**Comment by splitt3r** [comment]
@jospoortvliet i think https://nextcloud.com/usermanagement/ is the better choice for the first link on the groupware page?

**Comment by jospoortvliet** [comment]
@splitt3r god yes... Absolutely... Can you make that happen?

**Comment by splitt3r** [comment]
Done.

**Pull request merged**
