### PR TITLE
add section on verticals to be included on other pages

### PR DESCRIPTION
**Pull request by jospoortvliet**
We have two vertical pages right now; I've added them to a little section one could add on the bottom of pages. But it is commented out, for now, as I first want to have some more vertical pages ;-)

### CODE REVIEW

**Comment by MariusBluem** [comment]
Please put this on staging and guide me what to test over here ....

**Comment by jospoortvliet** [comment]
It is commented out... Let's just leave it here until we can actually use it.

**Comment by jospoortvliet** [comment]
Updated for our two new verticals. I have put it on our front page but it has to go on other pages too, of course. Let's first see what we think of this, here... Then we can do the rest.

screenshot_20180216_112702

**Comment by Espina2** [comment]
@jospoortvliet 

Give a line breaks on the learn more buttons. It will look better. :)

**Comment by jospoortvliet** [comment]
screenshot_20180218_143506

I dunno, it doesn't strike me as more awesome to be honest. Are you sure?

**Comment by jospoortvliet** [comment]
screenshot_20180228_101731

What do we think?

**Comment by jospoortvliet** [comment]
(and pls don't merge this PR, something went wrong and I'm actually working in the verticals2 branch)

**Comment by MariusBluem** [comment]
👍

**Comment by jospoortvliet** [comment]
Going live ;-)

**Pull request closed without merging**
