### PR TITLE
Fix 46, keep mobile menu until 1024px device width

### PR DESCRIPTION
**Pull request by mikebabb**
This is a fix for issue #46 that keeps the mobile menu button showing up until 1024px device width. Currently, it disappears and the site shows the "full" menu layout as of 768px, but as you can see from @mar1u5's screenshot the menu layout doesn't quite work at that size. 

I couldn't find the source file for the CSS initially and committed the fix in in the minified CSS file, which would have been overwritten as soon as somebody ran the grunt command to minify CSS again. Commit 	5a78685 corrects this by making the changes in navbar.less, where they should have been. Apologies for the mixup there.

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Pff, I only recently figured out grunt and nearly never run it. Best to make CSS changes in styles.css, that's where I do it ;-)

**Comment by mikebabb** [comment]
In my day job I'm a pretty heavy grunt user, but I have a special hatred for bootstrap!

Does it particularly need updating? Should I apply this fix another way?

**Comment by jospoortvliet** [comment]
I've only recently updated it so it is unlikely that it will happen any time soon - but, you know, some day... And then this fix would disappear ;-)

I think it's best to just put it in styles.css,  I know it is perhaps not super correct but it'll work and be retained in the future.

**Comment by mikebabb** [comment]
Commit 4cddb73 adds menu CSS overrides to styles.css as requested. This way, updates to Bootstrap in future shouldn't cause the iPad portrait menu layout fix to be undone when navbar.less is updated.

**Comment by jospoortvliet** [comment]
Awesome ;-) :+1:

**Comment by jospoortvliet** [comment]
This change made the top bar move when items in the menu were hovered on my system, fixed in https://github.com/nextcloud/nextcloud.com/commit/49431b634931cd50468d5c5ad1bbf417b8634bff
(also re-ran grunt)

**Pull request merged**
