### PR TITLE
update design page

### PR DESCRIPTION
**Pull request by jospoortvliet**
Signed-off-by: Jos Poortvliet <jospoortvliet@gmail.com>

@jancborchardt as promised.
screen shot 2017-11-23 at 19 06 55-fullpage 1

### CODE REVIEW

**Comment by jospoortvliet** [comment]
I only did the basics - introduce the new design. And put in an image ;-)

The rest I leave to the design team 😁

**Comment by jancborchardt** [comment]
Thanks! Will take it from here :)

**Comment by jancborchardt** [comment]
@jospoortvliet I adjusted the headings and removed the empty section. Would it be possible that instead of the unrelated group picture we embed this short design team intro talk? https://www.youtube.com/watch?v=5SAB0CY-iZ0 – after that it would be good to go. :)

**Comment by jospoortvliet** [comment]
Can do.

I have put the current code on staging: https://nextcloud.com/contribute/design/?staging=true

**Comment by jancborchardt** [comment]
Fixed some more small things! :) Want to put it on staging for a last check @jospoortvliet? It’s good from my view.

**Comment by jospoortvliet** [comment]
changes on staging again. Test, merge, I will deploy!

**Comment by jospoortvliet** [comment]
If there are other changes - let's do them separate, this is a big improvement already.

**Comment by jancborchardt** [comment]
Good stuff, thank you! :)

@nextcloud/designers what do you think of the new https://nextcloud.com/design ? We can improve a bunch still but it's much better already. :) One important thing I'd say is to highlight our design documentation more. Maybe via one of these Blue sections inbetween. :)

**Pull request merged**
