### PR TITLE
More team members' details

### PR DESCRIPTION
**Pull request by jospoortvliet**
- [x] Brian
- [x] @leonklingele
- [x] Andreas
- [x] @jancborchardt 
- [x] @Ivansss 
- [x] @MorrisJobke 
- [x] Joachim
- [x] @longsleep  (see email!!!)

### CODE REVIEW

**Comment by leonklingele** [comment]
I prefer to not post a picture of myself.
However, I will provide some text later today.

**Comment by LukasReschke** [comment]
@jancborchardt, @MorrisJobke You're still missing :)

**Comment by MorrisJobke** [comment]
> @jancborchardt, @MorrisJobke You're still missing :)

I know 🙈

**Comment by MorrisJobke** [comment]
> @jancborchardt, @MorrisJobke You're still missing :)

I send a rough draft to Jos and he will polish it language wise 🙈

**Comment by jospoortvliet** [comment]
@leonklingele I need a text about you, we all know you're awesome but the page has to be professional and awesome people don't work at professional companies ;-)
:see_no_evil: :hear_no_evil: :speak_no_evil:

**Comment by jancborchardt** [comment]
@jospoortvliet added my description and corrections

**Comment by MorrisJobke** [comment]
Thanks @jospoortvliet 👍

**Comment by jancborchardt** [comment]
Can we push this? Would be nice to have that page before the conference, no?

**Comment by jospoortvliet** [comment]
Decision for @karlitschek

**Comment by karlitschek** [comment]
i would suggest to go over it again on the weekend and then do it. Hope this makes sense!

**Comment by LukasReschke** [comment]
I rebased this upon master.

**Comment by LukasReschke** [comment]
I deployed this on staging for testing.

About: https://nextcloud.com/about/?staging=true
Team page: https://nextcloud.com/team/?staging=true

@karlitschek @jospoortvliet Your choice to put this live or not.

**Comment by Espina2** [comment]
If I can suggest, its pretty nice if you have photo of the team together on the top. And I suggest to add a maximum height of the columns to not past the actual size of the text. Maybe some tweaks on the shadow I think its to aggressive.

**Comment by jancborchardt** [comment]
Got rid of the box-shadow completely since we don’t really use that anywhere and whitespace works well.

@schiessle can we cut your text just a little bit? It seems to be longer than the others resulting in an overall higher size of the entries. Then we can make them all a bit less tall. ;) cc @jospoortvliet 

Also I’d say we simply link the name with the website so we don’t waste a full row with one icon. Unless we’ll add Twitter/Github of course.

**Comment by jospoortvliet** [comment]
@georgehrke could you add your details? I created an spot for you and filled in most details ;-)

**Comment by jospoortvliet** [comment]
I think we should keep twitter/github, so keep that row.

It looks nice this way! Now let's merge before I again have to add people again by the end of the month, that way it is never finished :paintbrush: 

/me waits for a go from F

**Comment by georgehrke** [comment]
>  filled in most details ;-)

Looks good :)
But we definitely have to take a proper picture at the next hackathon. ;)

**Pull request merged**
