### PR TITLE
Fix syntax error on footer.php

### PR DESCRIPTION
**Pull request by ldonis**
Comment end tag for the documentation menu.

### CODE REVIEW

**Comment by jancborchardt** [comment]
If you refer the issue in the pull request by using #5, it will be linked on Github :)

**Comment by jancborchardt** [comment]
And looks good, thanks a lot for the contribution! :) :+1:

**Comment by jancborchardt** [comment]
Ah right, if you put »fix #5« in the commit or pull request description, the issue will also be closed automatically.

**Comment by ldonis** [comment]
Thanks a lot for the tips!
I will do a better job in my next contribution.

**Comment by jancborchardt** [comment]
Ah don’t worry, great job! Just some Github tips. ;)

**Pull request merged**
