### PR TITLE
Use direct link to Newsletter

### PR DESCRIPTION
**Pull request by LukasReschke**
Link directly to the subscribe form. As brought up by @jancborchardt 😉 

cc @jancborchardt @jospoortvliet

### CODE REVIEW

**Comment by mar1u5** [comment]
👍 Makes sense, since users who want to unsubscribe can fetch the link to unsubscribe from the newsletters 😉 ...what about directly embed the subscription into the website?

**Comment by jospoortvliet** [comment]
:+1: awesome indeed...  And @mar1u5 is right, it'd be even nicer to be able to subscribe right there and then but I have no clue how to make that happen so until then, this'll do the trick...

**Comment by mar1u5** [comment]
http://docs.phplist.com/CustomSubscribeForm.html @jospoortvliet 😉

**Comment by jospoortvliet** [comment]
I will put that in the issue list then...

**Comment by jancborchardt** [comment]
Awesome – yes great point by @mar1u5 to directly integrate it :)

**Pull request merged**
