### PR TITLE
Fix download URLs for daily-builds

### PR DESCRIPTION
**Pull request by mar1u5**
cc @jospoortvliet

### CODE REVIEW

**Comment by mar1u5** [comment]
⚠️ ⚠️ 

cc @jancborchardt @LukasReschke @MorrisJobke

**Comment by MorrisJobke** [comment]
Makes sense and would fix the daily URLs :+1:

**Comment by jancborchardt** [comment]
Seems good :+1: 

@jospoortvliet can you deploy to fix?

**Comment by jospoortvliet** [comment]
thanks for fixing! Deployed.

**Pull request merged**
