### PR TITLE
The Nextcloud Home/SME Server

### PR DESCRIPTION
**Pull request by enoch85**
The Nextcloud VM, now as a NUC!

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Pretty fine if you ask me... Just the image not (yet) ;-)

**Comment by enoch85** [comment]
@jospoortvliet Thanks Jos! Added you as a reviewer as I wanted to confirm it was OK. I plan to release a device which is the most powerful NUC of the existing devices. A SFF server, with 16 GB RAM, a decent CPU, M2 SSD, + 2 TB HDD and so on. Will work on the page once I'm done with the new Nextcloud VM release.

**Comment by enoch85** [comment]
@jancborchardt  Ready for testing. Does it look right to you?

**Comment by enoch85** [comment]
Please squash the commits if you decide to merge. Thanks!

**Comment by enoch85** [comment]
Waiting for feedback here. OK to merge?

**Pull request merged**
