### PR TITLE
Fix: update webchat link

### PR DESCRIPTION
**Pull request by mcnesium**
update webchat link from Riot to Element #610

### CODE REVIEW

**Review by jospoortvliet — APPROVED** [review]

**Comment by jospoortvliet** [comment]
Only thing is - I'm not sure if that channel really is used anymore, we're active in Nextcloud Talk now... Hmmm. Still, let's update this, it's at least an improvement! Thanks! Meanwhile @rakekniven might know what the best way is to reach out to translators.

**Comment by tcitworld** [comment]
There's people on Libera, but I don't see much going on Freenode.

**Comment by jospoortvliet** [comment]
Then perhaps we should point to the community chat, @tcitworld  ??

**Comment by tcitworld** [comment]
My opinion is that the help forums are probably the only viable thing, though I'm on most communication channels.

**Comment by rakekniven** [comment]
Transifex is no place for discussions. 
Functionally, it is light years behind discourse.
The help forums are an active place. 
The channel at https://cloud.nextcloud.com/call/xhz52vhg is not actively used. People cannot create accounts themselves, or?

So I would vote for a link to the forums.

**Pull request merged**
