### PR TITLE
fixes missing closing ul and identation

### PR DESCRIPTION
**Pull request by vincchan**

### CODE REVIEW

**Comment by vincchan** [comment]
@jospoortvliet FYI

**Comment by jancborchardt** [comment]
Looks good! :+1: 

Btw it seems like we use spaces here? The Nextcloud code style guidelines say tabs. ;)

**Comment by vincchan** [comment]
@jancborchardt Indentation in this repo is funny anyway, for example [base.php](https://github.com/nextcloud/nextcloud.com/blob/master/base.php) is a mix of spaces and tabs... 🙅

**Comment by jancborchardt** [comment]
@vincchan so @jospoortvliet deserves a slap for that :D

**Comment by jospoortvliet** [comment]
Yeah, bloody mess, my fault as always.

**Pull request merged**
