### PR TITLE
translation compatible URL's on many pages

### PR DESCRIPTION
**Pull request by jospoortvliet**
Hi team,

To make links properly redirect on a translated site, I had to modify- well, almost every page on the site... "fun" Saturday+Sunday task.

I'll deploy it on staging, any chance you guys can make a nice list of pages to check and go through them?
What to check:
* does the page even display (yes, if I made a BIG mistake the page doesn't work at all)
* are links correctly going to the de subdomain

Here's an example of a page where it looks good:
https://nextcloud.com/de/storage/?staging=true
* [x] page loads, yay
* [x] links like those in the first paragraph to workflow & monitoring link to the de variant

A lot of small changes will require updating translations on the pages... sorry :(

TODO:

* [x] cliens page has a few unconverted links (waiting for review/approval/merge of https://github.com/nextcloud/nextcloud.com/pull/740)

Signed-off-by: Jos Poortvliet <jospoortvliet@gmail.com>

### CODE REVIEW

**Comment by tflidd** [comment]
I'm not really sure what we are supposed to check. I started from this page:
https://nextcloud.com/de/storage/?staging=true

All the links and those of the following sites stay within the german version, that looks good for me.

Regarding the general loading, I have a very strange behaviour. If I just load the page, it seems to only load a rough design framework without the content (or only parts of it). So the page after reloading looks like this:
before

When I start to scroll it starts to show the content:
after

I have the same problem, when I use the normal webpage https://nextcloud.com/storage/ so I suppose it is a different issue and not related to your changes.

**Comment by jospoortvliet** [comment]
Before this doesn't work on all files, would someone (@MariusBluem or @mathiasconradt perhaps) have some time to test a bunch of pages below and report back? I'm worried this will break too much...

Deployed on staging again.

- [ ] https://nextcloud.com/de/files/?staging=true
- [ ] https://nextcloud.com/de/groupware/?staging=true
- [ ] https://nextcloud.com/de/talk/?staging=true
- [ ] https://nextcloud.com/de/athome/?staging=true
- [ ] https://nextcloud.com/de/globalscale/?staging=true
- [ ] https://nextcloud.com/de/secure/?staging=true
- [ ] https://nextcloud.com/de/features/?staging=true
- [ ] https://nextcloud.com/de/file-drop/?staging=true
- [ ] https://nextcloud.com/de/sharing/?staging=true
- [ ] https://nextcloud.com/de/collaboraonline/?staging=true
- [ ] https://nextcloud.com/de/outlook/?staging=true
- [ ] https://nextcloud.com/de/enterprise/?staging=true
- [ ] https://nextcloud.com/de/about/?staging=true
- [ ] https://nextcloud.com/de/support/?staging=true
- [ ] https://nextcloud.com/de/team/?staging=true
- [ ] https://nextcloud.com/de/events/?staging=true
- [ ] https://nextcloud.com/de/workflow/?staging=true all
- [ ] https://nextcloud.com/de/clients/?staging=true all
- [x] https://nextcloud.com/de/storage/?staging=true all
- [ ] https://nextcloud.com/de/monitoring/?staging=true all
- [ ] https://nextcloud.com/de/pricing/?staging=true
- [ ] https://nextcloud.com/de/enterprise/buy/?staging=true
- [ ] https://nextcloud.com/de/contribute/?staging=true
- [ ] https://nextcloud.com/de/contributors/?staging=true
- [ ] https://nextcloud.com/de/partners/?staging=true
- [ ] https://nextcloud.com/de/install/?staging=true
- [ ] https://nextcloud.com/de/release-channels/?staging=true
- [ ] https://nextcloud.com/de/conf/?staging=true
- [ ] https://nextcloud.com/de/security/?staging=true
- [ ] https://nextcloud.com/de/security/advisories/?staging=true
- [ ] https://nextcloud.com/de/security/threat-model/?staging=true
- [ ] https://nextcloud.com/de/compare/?staging=true
- [ ] https://nextcloud.com/de/enterprise/buy/?staging=true
- [ ] https://nextcloud.com/de/trademarks/?staging=true
- [ ] https://nextcloud.com/de/press/?staging=true
- [ ] https://nextcloud.com/de/changelog/?staging=true
- [ ] https://nextcloud.com/de/box/?staging=true
- [ ] https://nextcloud.com/de/privacy/?staging=true
- [ ] https://nextcloud.com/de/confinfo/?staging=true
- [ ] https://nextcloud.com/de/design/?staging=true
- [ ] https://nextcloud.com/de/partners/?staging=true
- [ ] https://nextcloud.com/de/enterprise/order/?staging=true
- [ ] https://nextcloud.com/de/hackathon/?staging=true
- [ ] https://nextcloud.com/de/events/conference-program/?staging=true
- [ ] https://nextcloud.com/de/events/conference-program/speaking/?staging=true
- [ ] https://nextcloud.com/de/connect/?staging=true
- [ ] https://nextcloud.com/de/devices/?staging=true
- [ ] https://nextcloud.com/de/federation/?staging=true
- [ ] https://nextcloud.com/de/impressum/?staging=true
- [ ] https://nextcloud.com/de/providers/apply/?staging=true
- [ ] https://nextcloud.com/de/events/meetups/?staging=true
- [ ] https://nextcloud.com/de/securesharing/?staging=true
- [ ] https://nextcloud.com/de/spreedbox/?staging=true
- [ ] https://nextcloud.com/de/code-of-conduct/?staging=true
- [ ] https://nextcloud.com/de/healthcare/?staging=true
- [ ] https://nextcloud.com/de/education/?staging=true

If all boxes are ticked (or fixed) we can push this live and our German site should work pretty good.

**Comment by mathiasconradt** [comment]
@jospoortvliet Ok, so just to confirm, the review task here is basically to check whether all internal links on the listed pages have the "/de/" in the path, right.

**Comment by jospoortvliet** [comment]
Correct and correct!

**Comment by mathiasconradt** [comment]
I use this comment to list the pages where links are not correct (in progres, still testing):

- [ ] https://nextcloud.com/de/features/?staging=true

**Comment by jospoortvliet** [comment]
- [x] https://nextcloud.com/de/features/?staging=true (all links)
 - page removed ;-)
- [x] https://nextcloud.com/de/about/?staging=true (global scale link)
 - fixed
- [x] https://nextcloud.com/de/contribute/?staging=true (code of conduct link)
 - Fixed, though page will remain English, if you can't read English you can't really get much involved in Nextcloud... We're an international community using English as our language for collaboration.
- [x] https://nextcloud.com/de/partners/?staging=true (box link, low prio though, since box is dead)
 - fixed
- [x] https://nextcloud.com/de/hackathon/?staging=true (page not found)
 - removed 😄 
- [x] https://nextcloud.com/de/impressum/?staging=true (contact form link)
 - fixed
- [x] https://nextcloud.com/de/spreedbox/?staging=true (contribute link)
 - fixed

Thanks!!!

**Pull request merged**
