### PR TITLE
two job openings and more

### PR DESCRIPTION
**Pull request by jospoortvliet**
We're hiring, of course ;-)

Added two concrete job openings and a general "hey we're hiring".

Yeah, it's a bit boring, a picture might be nice... Later maybe.

### CODE REVIEW

**Comment by karlitschek** [comment]
nice 👍

**Comment by jospoortvliet** [comment]
nextcloud

**Comment by mar1u5** [comment]
👍

**Comment by blizzz** [comment]
Does the email exist already? :D

**Comment by jospoortvliet** [comment]
It does ;-)

**Comment by blizzz** [comment]
Personally, I do not like the "Linux expert" title. It obviously describe what is needed, however these days "expert" is used very inflationary, and is a target for jokes, actually. Why not just "Linux Kernel and Embedded Engineer", for instance?

**Comment by jospoortvliet** [comment]
https://github.com/nextcloud/nextcloud.com/commit/d048cb39094b3b709f332e42b630e7f03d45aebb fixes that then ;-)

**Pull request merged**
