### PR TITLE
Fix #502

### LINKED ISSUE #502: when you scroll to a # it might not show anything
https://nextcloud.com/sharing/#federation gives me a nearly empty page due to the 'appear on scroll' javascript...

### PR DESCRIPTION
**Pull request by Espina2**
@jospoortvliet This should fix the issue of the empty content when send links in anchor tags. 
Please review if are this that you want.

### CODE REVIEW

**Comment by jospoortvliet** [comment]
no workie here... in chrome.

spectacle bz1690

**Comment by jospoortvliet** [comment]
👍 now it works!

**Comment by Espina2** [comment]
Going to do that now. :)

**Comment by jospoortvliet** [comment]
Argh now it seems broken again?!?!

**Comment by jospoortvliet** [comment]
hmmm and if you go to http://localhost:5000/sharing/#bla it replaces the federation ID with bla. Hmm, not entirely what it should do but also not a big problem.

Looking at the JS, maybe I can figure this out :D

**Comment by jospoortvliet** [comment]
OMG OMG I FIXED IT
so if you go to sharing/#federation it just scrolls to the right spot, as it should, no replacement of the example. If you go to sharing/#something@something.com it scrolls AND replaces.

**Comment by Espina2** [comment]
@jospoortvliet Nice. :) So go ahead and merge this.

**Pull request merged**
