### PR TITLE
improve footer

### PR DESCRIPTION
**Pull request by jospoortvliet**
Adding some links & re-arranging them. Whadda yah think?

### CODE REVIEW

**Comment by mar1u5** [comment]
Can we add GitHub too? :grin:

**Comment by jancborchardt** [comment]
True, there should be:
- About
  - the curent links
- Contact
  - Twitter
  - Google+
  - Press
  - IRC #nextcloud
- Contribute
  - Forum
  - Github
  - IRC #nextcloud-dev

How bout that @jospoortvliet?

**Comment by jospoortvliet** [comment]
Let's not go and add 10 more items - we also need space for the user, admin and developer manual, faq, swag store and security page. Those pages aren't there yet but will be. In short, the empty space in the middle has 7 items already - they are just hidden right now as we are not ready for that stuff yet.

There is a big contribute link on top of every page. Twitter, G+, they are as big icons just above there, too. IRC - once is enough imho.

**Comment by vincchan** [comment]
@jospoortvliet LGTM

**Comment by mar1u5** [comment]
GitHub should be there .. It is essential :grin: @jospoortvliet

**Comment by jospoortvliet** [comment]
@mar1u5 true, true... but that's on top of the page, under contact, right? ;-)

So I added docu & link to GH https://github.com/nextcloud/nextcloud.com/commit/f8904672bb61c1f7398584fa092719374e169a09

what do you think, good enough?

**Comment by mar1u5** [comment]
:+1:

**Pull request merged**
