### PR TITLE
Conference page

### PR DESCRIPTION
**Pull request by jospoortvliet**
Create/update our conf page. Pls have a look @Espina2 @jancborchardt @MariusBluem 
conf nextcloud 21-3-2017 13-55-28

### CODE REVIEW

**Comment by jospoortvliet** [comment]
and @NinaNC for text ;-)

**Comment by NinaNC** [comment]
96eb6c9a-0e3e-11e7-8d86-0923c6851811

Nice page! I commented the screenshot :) Sorry for the aggressive red, I wanted to make it visible.

**Comment by jancborchardt** [comment]
Let’s make the group picture the header image? Currently we have 2 big pictures with exclusively men on it. :(

Also:
- [ ] The top image text »Be part of our community« seems not really needed. Why don’t we directly put the crucial info in the block below with »Nextcloud Conference« etc there. Then it’s like on the frontpage – all important info directly there
- [ ] cut the »The« in front of »Nextcloud Conference«
- [ ] add »Technical University« so it says »Technical University Berlin« so you instantly know where it is
- [ ] i’d put the »Submit a talk« button next to the »Register« button
- [ ] let’s call the button »Register for free«. And we don’t need to have this »Register« section on the bottom at all.
- [ ] some nice colored buttons for twitter / facebook etc like we have on other pages on the bottom?

**Comment by jospoortvliet** [comment]
Responses to Jan:
* I put as much info in the top, but it simply doesn't have room for too much.
* done
* done
* done
* done but I kept the section (reworded it a little) as I want to remind ppl to register and tell them why.
* these buttons are no longer part of our new theme/design... So they're not on other pages, not anymore. We have text links. I could of course include them here if you think that's useful.

**Comment by jospoortvliet** [comment]
Implemented all feedback from Nina.

**Comment by jospoortvliet** [comment]
Right now it looks like this:
conf nextcloud 21-3-2017 18-58-58
Feedback again welcome.

**Comment by jospoortvliet** [comment]
TODO:
* [ ]  add white space
* [ ] location and participation are difficult to understand for each image stand the text for
* [ ] The titles have a weird line-height for example on Development and Talks
* [ ] add an offset on one column for each side so the middle can breathe more

**Comment by jospoortvliet** [comment]
Any other comments? If not - I'd like to push this to live...

**Comment by jospoortvliet** [comment]
@Espina2 OK'ed as is so - going for master!

**Pull request merged**
