### PR TITLE
Remove duplicate entry

### PR DESCRIPTION
**Pull request by MorrisJobke**
compare with line 64 ;)

cc @Espina2 @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
And this fixes the text on the buttons of the enterprise page. It's now better centered.

**Comment by LukasReschke** [comment]
THX! Deployed.

**Comment by Espina2** [comment]
Don't remove the padding value in all the buttons the visual height of the arrow have to be compensated with less margin in the left. The label should not be centered so the button doesnt look centered.

**Comment by Espina2** [comment]
Ah forget its something that repeated. :) Sorry

**Pull request merged**
