### PR TITLE
A basic 404 page to fix #532

### LINKED ISSUE #532: Error page is broken
As you can see in the screenshot the error page seems broken. It looks ugly and the footer isn´t showing up.

Example: https://nextcloud.com/feasas

Error Page

### PR DESCRIPTION
**Pull request by mikebabb**
It's not much, but it's tidier than the broken page currently shown for non-existent pages.

### CODE REVIEW

**Comment by MariusBluem** [comment]
@jospoortvliet SEO-wise feedback would be nice 😅

**Comment by jospoortvliet** [comment]
I can't test at the moment (holiday...) but perhaps @NinaNC can? A screenshot would help too.

Either way, I think it can't be worse than our current page so I'm already happy enough to 👍 it 🤣

**Comment by mikebabb** [comment]
You're right, a screenshot would have been helpful! If this is still open tomorrow night when I can add one, I'll do that 👍

**Comment by MariusBluem** [comment]
bildschirmfoto 2017-11-01 um 10 45 48

**Comment by jospoortvliet** [comment]
Looks good as far as I am concerned, let's go!

**Comment by MariusBluem** [comment]
Thanks @mikebabb 💪

**Comment by mikebabb** [comment]
Happy to help! 😁

**Pull request merged**
