### PR TITLE
[RFC] added cdn for faster scripts loads

### PR DESCRIPTION
**Pull request by Espina2**
Added CDN for faster scripts loading.
@jospoortvliet please merge and try

### CODE REVIEW

**Comment by jospoortvliet** [comment]
It worked for a minute but then the features page didn't work giving this error:
spectacle r26962

Now other pages also have stopped working.

Trying to use wget on these URL's doesn't work, it gives a ERROR 403: forbidden.

I deployed on staging and it doesn't work there either - https://nextcloud.com/features/?staging=true gives a nearly white page.

Looks like the CDN blocked me already, after trying to load 4 or 5 pages.... I'm not sure this is helpful if that can happen to others, too ;-)

**Comment by Espina2** [comment]
The first error is a typo, going to fix that. It should give error, if for some reason it can't download from the cdn it use the file on vendor file. 

But I will dig on that in a minute.

**Comment by Espina2** [comment]
Fixed. @jospoortvliet

**Comment by Espina2** [comment]
This is ready for merge. @jospoortvliet

**Comment by jospoortvliet** [comment]
I'm not convinced it is faster.

https://nextcloud.com/features/?staging=true loads reliably in one second on Chrome while the normal page is done in 900ms.

On the comparison page in one load it is much faster and the other it is slower. This isn't a clear improvement at all.

More importantly, on https://nextcloud.com/globalscale/?staging=true and https://nextcloud.com/collaboraonline/?staging=true stuff is broken so I'm not comfortable with this change unless ALL pages on our website are checked individually.

Also, it seems CDN's block me now or something like that - at least, I have problems on other sites, too ;-) no clue if that is related or just an accident.

Error:
header.js:13
Uncaught TypeError: $(...).velocity is not a function
    at Object.init (header.js:13)
    at HTMLDocument.<anonymous> (header.js:266)
    at i (jquery.min.js:2)
    at Object.add [as done] (jquery.min.js:2)
    at n.fn.init.n.fn.ready (jquery.min.js:2)
    at header.js:3
    at Object.execCb (require.js?x16328:5)
    at b.check (require.js?x16328:5)
    at b.<anonymous> (require.js?x16328:5)
    at require.js?x16328:5
init @ header.js:13
(anonymous) @ header.js:266
i @ jquery.min.js:2
add @ jquery.min.js:2
n.fn.ready @ jquery.min.js:2
(anonymous) @ header.js:3
execCb @ require.js?x16328:5
check @ require.js?x16328:5
(anonymous) @ require.js?x16328:5
(anonymous) @ require.js?x16328:5
(anonymous) @ require.js?x16328:5
each @ require.js?x16328:5
emit @ require.js?x16328:5
check @ require.js?x16328:5
enable @ require.js?x16328:5
init @ require.js?x16328:5
h @ require.js?x16328:5
completeLoad @ require.js?x16328:5
onScriptLoad @ require.js?x16328:5
jquery.youtubepopup.js:6
 Uncaught TypeError: u.dialog is not a function
    at n.fn.init.init (jquery.youtubepopup.js:6)
    at n.fn.init.o.fn.YouTubePopup (jquery.youtubepopup.js:6)
    at ?staging=true:2
    at Object.execCb (require.js?x16328:5)
    at b.check (require.js?x16328:5)
    at b.<anonymous> (require.js?x16328:5)
    at require.js?x16328:5
    at require.js?x16328:5
    at each (require.js?x16328:5)
    at b.emit (require.js?x16328:5)

**Comment by Espina2** [comment]
@jospoortvliet The problem at that pages are the same on the features a bad require.js configuration. 

I can fix that, but the changes It will be more notable on the slow connections I guess. On the fast ones it should = as it is now.

**Comment by Espina2** [comment]
It's fixed if is there any other page that the youtube plugin is needed, I need to fix the require configuration in that particular case.

I just run a quick test for seeing the difference, and it improves a bit as you can see.

But feel free to add merge it if you want don't want it @jospoortvliet .

screen shot 2017-06-16 at 23 45 54
screen shot 2017-06-16 at 23 46 10

**Comment by enoch85** [comment]
Should we go ahead and merge this @jospoortvliet ?

**Comment by jospoortvliet** [comment]
Deploying so we can test today.

**Comment by jospoortvliet** [comment]
Everybody: help test please. Check if anything is broken... test order forms, enterprise page, youtube video popups...

**Comment by enoch85** [comment]
The about page have ALOT of whitespace, don't know how it looked like before: http://i.imgur.com/rkqZ1KG.png

**Comment by jospoortvliet** [comment]
You probably have to do a shift-reload, the top image isn't shown.

**Comment by enoch85** [comment]
@jospoortvliet Didn't help, already tried. Anyway, that's the only thing I could find. :)

**Comment by Espina2** [comment]
@enoch85 this should be another. Wich page is?

**Comment by enoch85** [comment]
@Espina2 https://nextcloud.com/about/

**Comment by enoch85** [comment]
And with the inspection tool in Chromium:

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/wp-content/themes/next/assets/js/vendor/jquery.youtubepopup.js:6 Uncaught TypeError: u.dialog is not a function
    at n.fn.init.init (/wp-content/themes/next/assets/js/vendor/jquery.youtubepopup.js:6)
    at n.fn.init.o.fn.YouTubePopup (/wp-content/themes/next/assets/js/vendor/jquery.youtubepopup.js:6)
    at (index):2
    at Object.execCb (require.js:5)
    at b.check (require.js:5)
    at b.<anonymous> (require.js:5)
    at require.js:5
    at require.js:5
    at each (require.js:5)
    at b.emit (require.js:5)
    at b.check (require.js:5)
    at b.enable (require.js:5)
    at b.init (require.js:5)
    at h (require.js:5)
    at Object.completeLoad (require.js:5)
    at HTMLScriptElement.onScriptLoad (require.js:5)
/wp-content/themes/next/assets/js/modules/header.js:13 Uncaught TypeError: $(...).velocity is not a function
    at Object.init (/wp-content/themes/next/assets/js/modules/header.js:13)
    at HTMLDocument.<anonymous> (/wp-content/themes/next/assets/js/modules/header.js:266)
    at i (jquery.min.js:2)
    at Object.add [as done] (jquery.min.js:2)
    at n.fn.init.n.fn.ready (jquery.min.js:2)
    at /wp-content/themes/next/assets/js/modules/header.js:3
    at Object.execCb (require.js:5)
    at b.check (require.js:5)
    at b.<anonymous> (require.js:5)
    at require.js:5
    at require.js:5
    at each (require.js:5)
    at b.emit (require.js:5)
    at b.check (require.js:5)
    at b.enable (require.js:5)
    at b.init (require.js:5)
    at h (require.js:5)
    at Object.completeLoad (require.js:5)
    at HTMLScriptElement.onScriptLoad (require.js:5)
```

**Comment by enoch85** [comment]
Also disabled all addons (Adblock and tracker) and it still doesn't work.

**Comment by enoch85** [comment]
Works on Pingdom though...

**Comment by jospoortvliet** [comment]
@Espina2 that might be a bug, could you look?

It works here on my linux but clearly not everywhere.

**Comment by Espina2** [comment]
@jospoortvliet @enoch I will take a look today. But it should be or cache or bad require.js in the file about.php file. Can you test on private just for discard the cache option.

**Comment by jospoortvliet** [comment]
So this broke https://nextcloud.com/devices and perhaps others @MariusBluem noticed. Can you tell me how to fix it as I have no idea... And this page gets thousands of visitors per day and now since 3 days they all get a white page :-1:  :-1:

**Comment by Espina2** [comment]
@jospoortvliet I said to test all the pages that have youtubes videos embed. The two pages, is one of the ones that have plugin. I fix the two, but i suggest again a quick review in all the pages that use the same plugin.

**Comment by jospoortvliet** [comment]
I will look tomorrow but I don't know exactly what pages have that plugin.. some of the feature pages I guess.

**Comment by Espina2** [comment]
@jospoortvliet I think these two are the last ones. But ping me if you see another one. If you want to fix the pages are pretty simple, copy the require config from another page that uses the same plugin, for example, globalscale, and duplicate the js and with the same name you give on the require config.

**Comment by MariusBluem** [comment]
Home, and...

/Features
/Secure
/Sharing
/Clients
/Workflow 
/Storage
/Monitoring
/collaboraonline
/webrtc
/outlook
/enterprise
/pricing
/globalscale
/Jobs

This is very critical!

**Comment by Espina2** [comment]
@MariusBluem If it are critical test in the pages you send me, and let me know wich ones are not working at the moment.

**Comment by camilasan** [comment]
I am sorry I don't have much time to help with it but here is my 2 cents:
@Espina2 It is really cool how much the website improved with your help, but you and @jospoortvliet should consider moving away from using so much Javascript.  It can slow down things significantly and it is a disservice to the user. A good website should work without JS too, which is not the case with Nextcloud.

@Espina2 It is volunteer work on a opensource project but it doesn't mean you don't have the responsibility you would have if this was a paid job. If you create a feature/make changes, you are responsible for making sure it is working. It is ok to break things but you need to improve your response time, other people depend on your work - as in, Nextcloud business can not run on a broken website.

**Comment by jospoortvliet** [comment]
@MariusBluem most of these pages work for me.

Broken are:
https://nextcloud.com/sharing/
https://nextcloud.com/about/

**Comment by jospoortvliet** [comment]
Fixed are devices and about, fixes deployed.

**Comment by Espina2** [comment]
@camilasan Just answering your thoughts, I never wanted to be not responsible for what I do, but at some point, I have to give priority to things that pay my bills. With that in mind, I can't give the attention needed for the tasks. For example, sometimes I made have the roles  Designer, front-end developer and Q&A, and this consumes to much time. 

> It is volunteer work on a opensource project but it doesn't mean you don't have the responsibility you would have if this was a paid job. If you create a feature/make changes, you are responsible for making sure it is working. It is ok to break things but you need to improve your response time, other people depend on your work - as in, Nextcloud business can not run on a broken website.

This can sound's not cool, but if an enterprise needs a people 24h per day working and giving support on something they should hire someone for that purpose. It can't be the guy that gives the free time it has because all he have is her free time, when they don't have it he can't help. 

If my help is not welcome, I have no problem with stopping contributing if anyone were thinks that I broke the website and what I did is somehow bad for Nextcloud.  I always answer every question in a day or two, if you read the whole pull request I ask for review, and that is normal, you should review before merge, and even said if @jospoortvliet are not confortable with the solution for not merge it all... So don't say is my fault, because it doesn't sound cool at all, for the person that is here every single day for helping...

**Comment by camilasan** [comment]
@Espina2  I am sure your contributions are very much welcome. All I meant was for you to be more careful before creating a pull request. Ask for help if you don't have time to test it.

**Comment by Espina2** [comment]
@camilasan is exactly what I did. :)

**Pull request merged**
