### PR TITLE
Add events to navbar and footer

### PR DESCRIPTION
**Pull request by MariusBluem**
Follow up of #374 😉 @jospoortvliet @cyberanca 

Signed-off-by: Marius Blüm <marius@lineone.io>

### CODE REVIEW

**Comment by Espina2** [comment]
Before that I think It would be nice if the page can look like the new pages. 

Its that possible?

**Comment by jospoortvliet** [comment]
@Espina2 sure, I would not mind - we can do that during this week, perhaps, or next week...

After FOSDEM we should have some nice pictures to use ;-)

**Comment by jospoortvliet** [comment]
So it is after FOSDEM - working on those pictures ;-)

Sadly we don't have a good, high res crew/booth pic, I should've taken that but forgot :sob:

**Comment by jospoortvliet** [comment]
I've updated the Events page to our new style. It is live - review/comments welcome.

https://github.com/nextcloud/nextcloud.com/commit/2bfa4c5e20898aab5121ef6f443b703d0742cd8b

**Comment by jospoortvliet** [comment]
so let's merge now, the events page is there and is awesome ;-)

**Pull request merged**
