### PR TITLE
12 is no longer supported!

### PR DESCRIPTION
**Pull request by jospoortvliet**
when oh when do we merge this :grin: 

@MorrisJobke I suggest in a week or two...

### CODE REVIEW

**Comment by MariusBluem** [comment]
Added 8776162cf99d7740614fd9de2483cdd709ec243e to remove it from `page-security` too 😉

**Comment by MorrisJobke** [comment]
> @MorrisJobke I suggest in a week or two...

Yep ... maybe also a bit longer. Early next year? Technically once 13.0.9 and 14.0.5 will be released, because then it didn't received the update.

**Comment by jospoortvliet** [comment]
Well, if we find a security issue now, it won't be addressed, so I'd say there's risk already. Let's do it at release or shortly after 15 is out...

**Comment by tflidd** [comment]
> Well, if we find a security issue now, it won't be addressed, so I'd say there's risk already. Let's do it at release or shortly after 15 is out...

In this case, you can release it already because it is not supported any more. And when someone reads it today, the planning for an upgrade starts today and not after the release of NC 15! I see no benefit in holding it back.

**Comment by MorrisJobke** [comment]
> In this case, you can release it already because it is not supported any more. And when someone reads it today, the planning for an upgrade starts today and not after the release of NC 15! I see no benefit in holding it back.

True point 👍

**Pull request merged**
