### PR TITLE
[WIP] Collabora Online - Rework

### PR DESCRIPTION
**Pull request by MariusBluem**
Based on /outlook/ 😅 

- [x] Header Image
- [ ] Installation tutorial polishing 🤔 

Could you help out with an header image and the installation tutorial? @jospoortvliet 

Signed-off-by: Marius Blüm <marius@lineone.io>

### CODE REVIEW

**Comment by jospoortvliet** [comment]
On it, for a bit - I gotta leave for some errands but I think I can help you before I leave.

**Comment by jospoortvliet** [comment]
So... It took me a while but I made it work. It needs a new top image (I plagiarized a screenshot from the web, if you want - take a nice screenshot and I Gimp it in, or pick an entirely different top image if you like).

I made it look a bit better but it can still use some of your attention to detail and perhaps a thought or two from @Espina2

**Comment by Espina2** [comment]
Some things I see.

- [ ] The youtube video is misaligned

- [ ] All the screenshots should be inside of this https://cloud.paulomoura.com.pt/owncloud/index.php/s/UCgo0rbHWn6Ubeo

- [ ] Get quote are not correctly aligned in the container. 

- [ ] All the text after the Getting Started In 3 steps are to wide and no longer look like the new typographic style

- [ ]  I should see how to show the code better.

- [ ] The last call to action should be like the Get quote.

- [ ]  Why commands are in red???

**Comment by Espina2** [comment]
I updated the typography tags in the HTML, we should increase the white spacing between elements.

**Comment by jospoortvliet** [comment]
I'm going to work on some of the other points so we can merge this!

**Comment by jospoortvliet** [comment]
Just the screenshots, now, and we're done :rocket:

**Comment by jospoortvliet** [comment]
Some text fixes and putting in the screenshot. How about it, @Espina2 and @MariusBluem ??

https://nextcloud.com/collaboraonline/?staging=true

I'd like to get this in and live soon so if you have changes perhaps just make them :sweat_smile:

**Comment by jospoortvliet** [comment]
OK'ed by @Espina2 so - going live!

**Pull request merged**
