### PR TITLE
Datasheet additions

### PR DESCRIPTION
**Pull request by jospoortvliet**
Add datasheets:
* file access control
* WND and SharePoint
* Nextcloud 12

Also fixed typo's in auditing submission form.

### CODE REVIEW

**Comment by jospoortvliet** [comment]
@MariusBluem @NinaNC if you could have a look and spot any big issues... would rock. If OK, update branch & merge pls ;-)

**Comment by jospoortvliet** [comment]
spectacle h28767

So I added images to each whitepaper submission page :smiley_cat:

**Comment by MariusBluem** [comment]
The whole blue box is far too big 😉 

28246166-3db59e98-6a14-11e7-87c9-47b56e5bb201

**Comment by jospoortvliet** [comment]
Hmmm, that could look OK for a single datasheet, with the two I'd then remove one of them. Lemme make a screenshot what it could look like:
spectacle fw4632

You think it is better?

**Comment by Espina2** [comment]
I do the design for this, and I will update the PR Today. @jospoortvliet @MariusBluem

**Comment by jospoortvliet** [comment]
Awesome

**Comment by Espina2** [comment]
screen shot 2017-07-16 at 23 12 32

I havent add the time for finishing the code, so I leave the mockup here

**Comment by jospoortvliet** [comment]
Oh, I think I can do that ;-)

**Comment by Espina2** [comment]
@jospoortvliet I didn't see it, so I don't include it. Why is it needed?

**Comment by jospoortvliet** [comment]
Because we otherwise get shitloads of spam... ;-)

**Comment by jospoortvliet** [comment]
https://nextcloud.com/workflow/?staging=true for example:
spectacle g11561

They all look like that. Only the Global Scale one is still mostly the old look as it just didn't look nice the 'new' way:
spectacle n12085
(I will decrease the whitespace above and below a bit, this is a little too much)

**Comment by jospoortvliet** [comment]
@MariusBluem @Espina2 could you approve so I can merge?

**Comment by jospoortvliet** [comment]
The latest changes have been deployed to staging. You can find them here:
https://nextcloud.com/?staging=true
https://nextcloud.com/?staging=true
https://nextcloud.com/?staging=true
https://nextcloud.com/?staging=true

**Comment by jospoortvliet** [comment]
The latest changes have been deployed to staging. You can find the datasheets on these pages:
https://nextcloud.com/features?staging=true
https://nextcloud.com/globalscale?staging=true
https://nextcloud.com/storage?staging=true
https://nextcloud.com/worflow?staging=true
https://nextcloud.com/monitoring?staging=true
https://nextcloud.com/education?staging=true
https://nextcloud.com/enterprise?staging=true

Please help test. It all works well locally. Don't forget to use shift-F5 (hard refresh) if you see problems, to verify they're not due to cached css or other files.

You can't submit the forms. That I'd like us to test quickly when it is put live.

**Comment by jospoortvliet** [comment]
Ok, merged to master. Now going live...
Then testing again:
https://nextcloud.com/features
https://nextcloud.com/globalscale
https://nextcloud.com/storage
https://nextcloud.com/workflow
https://nextcloud.com/monitoring
https://nextcloud.com/education
https://nextcloud.com/enterprise

**Pull request merged**
