### PR TITLE
[WIP/NI] Better Handling of dependencies

### PR DESCRIPTION
**Pull request by Espina2**
- [x] Remove the timeout from requireJS
- [x]  Use yarn for handling dependencies
- [x] Update jquery version and remove deprecated code
- [x] Use lodash instead of underscore
- [x] Using slim versions of libs instead of importing the whole library
- [x] Organise scss files by page
- [x] Use only the parts of bootstrap needed instead of importing everything
- [x] Remove vendor files from repo
- [x] Ident all the scss files correctly
- [x] Improve animations
- [x]  Inline SVGS for fewer http requests
- [x]  Optimized svgs
- [x]  Code Highlighting

### CODE REVIEW

**Comment by MariusBluem** [comment]
Is this ready to review? 🤔

**Comment by Espina2** [comment]
@MariusBluem 
You can review all the pages on menu features. I do the enterprise ones tomorrow. But wait a bit, and I will provide a link for testing purposes. :)

**Comment by jospoortvliet** [comment]
Wow @Espina2 is on a cleanup quest ;-)
vsnkpvc26yvbudcdrvnm

**Comment by Espina2** [comment]
@MariusBluem @jospoortvliet 
testing link http://staging.paulomoura.com.pt/wordpress/

**Comment by Bentong021** [comment]
https://github.com/nextcloud/nextcloud.com/pull/531

**Comment by Bentong021** [comment]
https://github.com/nextcloud/nextcloud.com/pull/531

**Comment by MorrisJobke** [comment]
@jospoortvliet Could you put this on staging? On @Espina2 server it is already a lot faster according to webpage speed (6s -> 2s) but I guess there is more possible with our tweaked server setup.

**Comment by Espina2** [comment]
@morrisjobke it's not completely done. My server is a raspberry pi, with a worst internet, so it should be more faster on the server.

**Comment by jospoortvliet** [comment]
I think I deployed on staging... Not sure how to be sure 😉

**Comment by Espina2** [comment]
You have to do extra stuff on the first deploy.

**Comment by MorrisJobke** [comment]
What extra stuff? 😉

**Comment by Espina2** [comment]
Install yarn
https://yarnpkg.com/lang/en/

And run yarn install

**Comment by Espina2** [comment]
Done in this PR
https://github.com/nextcloud/nextcloud.com/pull/571

**Pull request closed without merging**
