### PR TITLE
Gdpr tuning

### PR DESCRIPTION
**Pull request by jospoortvliet**
Hi awesomes!

I created a new GDPR page, besides a refactor the compliance section into a separate php file.

Love to hear what you think of the page!

gdpr-tinypng

### CODE REVIEW

**Comment by jasonbayton** [comment]
The title is not clear due to the busy background image, also "data" is not capitalised about half way down

**Comment by jospoortvliet** [comment]
Fixed the capitalization. Better image:
screenshot_20180604_103414

**Comment by jasonbayton** [comment]
Awesome. It does go on quite a bit and likely duplicates the message from other pages, but if that's the intention then no worries. Last niggle - I think "self hosted" should be "self-hosted", what do you think?

**Comment by jospoortvliet** [comment]
Agreed :D

**Pull request merged**
