### PR TITLE
[Need testing] Slideshow fix

### PR DESCRIPTION
**Pull request by Espina2**
@jospoortvliet 

Fixed the slideshow problem between 992px to 1200px

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Tested, works on my laptop... Let's merge.

**Comment by jospoortvliet** [comment]
deployed and tested on staging.

**Comment by jospoortvliet** [comment]
more testing welcome @nextcloud/website ;-)

**Comment by MariusBluem** [comment]
Works on iPad 9.7 👌

**Comment by jospoortvliet** [comment]
Ok THAT IS IT I AM PUTTING IT LIVE ;-)

**Comment by jospoortvliet** [comment]
done...

**Comment by jospoortvliet** [comment]
Thanks a lot, @Espina2 for the fix!!! I know it wasn't easy and I couldn't have done it...

**Comment by MariusBluem** [comment]
Awesome work 👍

**Comment by Espina2** [comment]
The blue indicators are gone. Still need to fix that.

**Pull request merged**
