### PR TITLE
sorted teams a bit better

### PR DESCRIPTION
**Pull request by wiswedel**
Signed-off-by: Sascha Wiswedel <sascha.wiswedel@nextcloud.com>

### CODE REVIEW

**Comment by wiswedel** [comment]
@ecblack Could you please add some info about you on the Team page? I already added you but you need to fill in some text. Just checkout this branch and commit to it.

**Comment by wiswedel** [comment]
by the way: Is Patrick as "Sales Manager" still correct?

**Comment by jospoortvliet** [comment]
> by the way: Is Patrick as "Sales Manager" still correct?

mja, maybe not, but I believe he didn't want to be something like accounting. So let's keep it. Thanks for the PR, will check and merge now.

**Comment by jospoortvliet** [comment]
also, what logic did you use to sort 'teams'? Before, I had senior management first, then sales, then marketing, then engineering, each of the alphabetically by first name... now it seems random, I mean, Markus Windecker is the 3rd person? I'll put the ordering back to something sane if you don't mind.

**Comment by jospoortvliet** [comment]
Was good to update things... So what I did now is:
* created a management team, with Frank first and the rest alphabetically.
* Created a sales team, alphabetically.
* Created a marketing team, alphabetically.
* engineering & support - also alphabetically.

We still have to add Nils, Kevin and Julien, so let's wait with merging this until they are added and then I'll put it live. We are at 42 team members, by the way 🛣 📖

**Comment by wiswedel** [comment]
Thanks for adding team headlines, @jospoortvliet. That's in the end what I intended :-)
If you don't mind, I'd like Sales Engineering to be in a separate section so it doesn't get mixed up with the AMs.

**Comment by jospoortvliet** [comment]
> Thanks for adding team headlines, @jospoortvliet. That's in the end what I intended :-)
> If you don't mind, I'd like Sales Engineering to be in a separate section so it doesn't get mixed up with the AMs.

are you sure? It seems a bit detailed - you also have ppl handling inbox etc... I can do it, of course, but if it says 'sales engineer' that seems to do the trick and I don't know what problem you exactly want to prevent?

**Comment by wiswedel** [comment]
Pre-Sales is a different profession than Account Management, even though of course both work closely together. It's important for the SE's trustworthiness towards the customer to maintain a strict boundary between Pre-Sales and Sales in the process.

So long story short, it's kind of a matter of the SE profession's self-conception.

**Comment by jospoortvliet** [comment]
> Pre-Sales is a different profession than Account Management, even though of course both work closely together. It's important for the SE's trustworthiness towards the customer to maintain a strict boundary between Pre-Sales and Sales in the process.
> 
> So long story short, it's kind of a matter of the SE profession's self-conception.

allright, I'll separate it!

**Pull request merged**
