### PR TITLE
Tub casestudy

### PR DESCRIPTION
**Pull request by jospoortvliet**
some more fixes

### CODE REVIEW

**Comment by jospoortvliet** [comment]
sigh. Messy. Had one more fix...

**Comment by MorrisJobke** [comment]
Please squash your commits 😉

**Comment by Espina2** [comment]
@MorrisJobke Why should we squash the commits?

**Comment by MariusBluem** [comment]
@Espina2 because there are 6 commits which change 1 line 😶 - and 5 of them are already in master via another commit. Makes no sense.

**Comment by MorrisJobke** [comment]
@jospoortvliet This is also possible right from the Github merge button 😉

**Comment by jospoortvliet** [comment]
I tried but couldn't get it to work, so I gave up and did another pr ;-)

**Comment by MorrisJobke** [comment]
bildschirmfoto 2017-07-19 um 14 06 24

**Comment by jospoortvliet** [comment]
Thanks 💃

**Pull request closed without merging**
