### PR TITLE
1204

### PR DESCRIPTION
**Pull request by jospoortvliet**
Let's get ready. Date isn't 100% clear but if RC2 gives no more surprises, Thursday should be doable.

@MorrisJobke once we're ready to go live, we can merge and deploy this 🥇 
But review is already welcome. It has 12.0.4 and 11.0.6 changelogs...

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> 11.0.6 changelogs...

there is a 11.0.6?

**Comment by MorrisJobke** [comment]
> there is a 11.0.6?

let me build that :)

**Comment by MorrisJobke** [comment]
I added the full changelog

**Comment by jospoortvliet** [comment]
@MorrisJobke how do you generate that changelog? The reason I made the short ones is that it has been entirely manual in the past and I (and you guys) have better things to do than formatting a load of html. If you have a quick way to do it, though, sure, it'd be nice to have full changelogs. But put that method/script/whatever somewhere please so everyone can use it 👍

**Comment by MorrisJobke** [comment]
> @MorrisJobke how do you generate that changelog? The reason I made the short ones is that it has been entirely manual in the past and I (and you guys) have better things to do than formatting a load of html. If you have a quick way to do it, though, sure, it'd be nice to have full changelogs. But put that method/script/whatever somewhere please so everyone can use it 👍

Copy paste from github, open in sublime text, select all lines with multi-line tool and enter the `<li>` and `<a>` around ... like a task of 2-4 minutes and you have a nicely formatted changelog.

**Comment by jospoortvliet** [comment]
> Copy paste from github, open in sublime text, select all lines with multi-line tool and enter the <li> and <a> around ... like a task of 2-4 minutes and you have a nicely formatted changelog.

I'm looking up what sublime text is... ;-)

**Comment by MorrisJobke** [comment]
Just an editor where I know a lot of shortcuts 😅

**Comment by MariusBluem** [comment]
> I added the full changelog

Very nice 👍

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/updater_server/pull/88

@jospoortvliet: I'm ready for the release - the archives are already in the prerelease folder and only need to by copied over to the releases folder. Then this and the updater server can go live.

**Comment by jospoortvliet** [comment]
Merged to master. Will now test locally, then on staging, then prepare blog & social and schedule all that for 11:30.

Meanwhile the packages are put in the right place and the update server is getting ready ;-)

**Pull request merged**
