### PR TITLE
Fixed home announcement message style

### LINKED ISSUE #776: Frontpage announcement has weird spacing
Just a quick find:
screen shot 2018-02-02 at 11 08 49

It seems this is realted to the line break:
screen shot 2018-02-02 at 12 09 11

Chrome 63 on Mac 10.12.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

@nextcloud/designers

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #776 

In progress

### CODE REVIEW

**Comment by jospoortvliet** [comment]
This is still WIP, right?

**Comment by skjnldsv** [comment]
@jospoortvliet Hum, I don't remember what I wanted to add to this! ^^'
You can review if you want :p

**Comment by jospoortvliet** [comment]
Nice work ;-)

Indeed fixes the handling of long announcements. Luckily the current one is short but the Talk one was way too long... and broke.

**Comment by skjnldsv** [comment]
This will need manual ajustement in case if we change the background image :)

**Pull request merged**
