### PR TITLE
pricing page: fixes and enhancements

### PR DESCRIPTION
**Pull request by wiswedel**
- wording fix
- better visibility for optional components

### CODE REVIEW

**Comment by jospoortvliet** [comment]
looking good and works. But if we add these, shouldn't we also add the outlook add-in (for all) and GS (for Premium)? And why is collabora available for basic, but not ONLYOFFICE?

**Comment by wiswedel** [comment]
@jospoortvliet as for GS, I agree, let's add that.
The other ones should be correct already 🤔
Do you have a screenshot?

**Comment by jospoortvliet** [comment]
Screenshot_20190910_151137

**Comment by wiswedel** [comment]
> Screenshot_20190910_151137

fixed by https://github.com/nextcloud/nextcloud.com/pull/1157/commits/b4c8119db7661a72f697696381ddeef778a5ea99

**Pull request merged**
