### PR TITLE
add Windows Mobile client link

### PR DESCRIPTION
**Pull request by jospoortvliet**
Adding WiMo client! ;-)

### CODE REVIEW

**Comment by jospoortvliet** [comment]
spectacle hf8902

**Comment by LukasReschke** [comment]
Not a huge fan since that implies official support TBH. For the record, any security ticket that will go in for this I'll just triage to you then 😉

**Comment by SunboX** [comment]
Looks good to me. The Windows Store Support is linked to the Github Issues for windows-uwp and to the Gitter Channel here: https://gitter.im/Nextcloud-App-UWP/Lobby

**Comment by Espina2** [comment]
Nice news!

**Comment by rullzer** [comment]
Please make it clear that we do not officially support this. We don't have the people nor the knowledge to maintain and fix this if it blows up or starts eatings the users kittens.

**Comment by MariusBluem** [comment]
Lets leave it there and make a little "Alpha. Not officially supported" sign under it ;) ... we can consider about that later, when the app is more stable and tested. 

Note: The enterprise-page does mention Windows Mobile-clients as available now 🤔

**Comment by LukasReschke** [comment]
> Note: The enterprise-page does mention Windows Mobile-clients as available now 🤔

See my rant at https://github.com/nextcloud/nextcloud.com/commit/279596b6441d0fa0ad851eefa1d1eae1549da414#commitcomment-19785094 as well ;)

**Comment by ChristophWurst** [comment]
How about moving it down to the third-party section?

**Comment by jospoortvliet** [comment]
Well it isn't 3rd party - it is developed in our repo by a community contributor. We could call it alpha, I suppose, though, as it is quite new. Let's do that...

**Comment by jospoortvliet** [comment]
... and I've put it lower, just above the 3rd party section. It doesn't look beautiful I'm afraid but it does the trick. We give it some time to mature and then give it a better spot ok?

**Comment by jospoortvliet** [comment]
spectacle jh7228

**Comment by MariusBluem** [comment]
Fixed some wording 👍

**Comment by jospoortvliet** [comment]
Let's get this live then.

**Comment by SunboX** [comment]
nice! thx, I'm happy that there's now a WP app ❤️ let's see how far we get with stabilisation, security and adding features

**Pull request merged**
