### PR TITLE
Revert "update Debian/Ubuntu repository link"

### PR DESCRIPTION
**Pull request by kesselb**
Reverts nextcloud/nextcloud.com#1199

1) This is the direct link to debian9. If this link would be correct we should probably use `https://download.opensuse.org/repositories/home:/ivaradi:/beta/`.

2) I don't see any 2.6.1 release at `https://download.opensuse.org/repositories/home:/ivaradi:/beta/`. Only a beta release for 2.7.0.

cc @misch7 @ivaradi what is the correct information for nextcloud.com?

### CODE REVIEW

**Comment by ivaradi** [comment]
@kesselb The stable repo (with 2.6.1) is at `https://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/` (i.e. without the `beta`).

**Comment by kesselb** [comment]
Thanks @ivaradi 

Out of curiosity what is the difference between `https://download.opensuse.org/repositories/home:/ivaradi/` and `https://download.opensuse.org/repositories/home:/ivaradi:/`?

The beta releases are with `ivaradi:` and the stable releases with `ivaradi` without the `:` at the end :thinking: I guess the PPA is still for the ubuntu users and the above repository for debian? Are there packages for Debian10 somewhere? :confused: 

Could you push a pull request with the correct information or post them here?

**Comment by ivaradi** [comment]
@kesselb 

I guess, the URLs are just the way th OpenSUSE build service works. The `beta` and `alpha` repositories are subprojects of `ivaradi`, and perhaps this is reflected by the colon when one of them is to be designated.

Yes, the PPA is for Ubuntu, and these repositories are for Debian. The `beta` repository contains packages for Debian 10 (`https://download.opensuse.org/repositories/home:/ivaradi:/beta/Debian_10/`), and hopefully the stable one will also have Debian 10 for the next release.

**Comment by jospoortvliet** [comment]
Ok - so I should merge this or should we include multiple links?

**Comment by kesselb** [comment]
> Ok - so I should merge this

I would say yes because without people will install beta releases.

**Comment by jospoortvliet** [comment]
thanks guys!

**Pull request merged**
