### PR TITLE
Two minor fixes

### PR DESCRIPTION
**Pull request by jospoortvliet**
fixing the color of links in the table on the pricing page, which look like the disabled color and confused some potential customer;
and adding linked-in to our website navigation (top and bottom).

Both very small changes, yes.

### CODE REVIEW

**Comment by jancborchardt** [comment]
@jospoortvliet can you post a before / after screenshot for quick review?

**Comment by jospoortvliet** [comment]
Old pricing page:
spectacle ea7252
New:
image

linked-in in the header:
image
footer:
image

Yes, there's this white space on the bottom of the menu - this I have locally in master, too, which is deployed and doesn't have it online. No clue why, nor do I care if it doesn't show up on our real site 🗡

**Comment by jancborchardt** [comment]
Looks good, but the spelling is "LinkedIn" (I know it's stupid but let's just do it like them).

**Comment by jospoortvliet** [comment]
Ok, will change that and add a youtube fix for the release channels page.
And fix on the front page that we say 'event' when it isn't 😄 
On it!

**Comment by jospoortvliet** [comment]
New changes have no real visual changes, all textual (or, well, making https://nextcloud.com/release-channels actually work).

**Comment by jospoortvliet** [comment]
If approved, just merge and I'll deploy after lunch ;-)

**Pull request merged**
