### PR TITLE
Remove Release Announcement

### PR DESCRIPTION
**Pull request by MariusBluem**
...otherwise, nobody will look at it, when we release the next version - or have some amazing news 😅 
@jospoortvliet 

Signed-off-by: Marius Blüm <marius@lineone.io>

### CODE REVIEW

**Comment by jospoortvliet** [comment]
we should wait until we have some other amazing news ;-)

**Comment by MariusBluem** [comment]
I think that when it is there always, the users do not longer look at it, since it does not stick out of the "normal" behaviour of the Homepage

**Comment by jospoortvliet** [comment]
Well, it's mostly for new users anyway - I doubt many existing users visit that page for anything other than to find the download page. I think we should always have something there and atm there's nothing really better.

**Comment by MariusBluem** [comment]
What do you think @jancborchardt ... do you also think we should keep this release announcement all the time 😕

**Comment by jospoortvliet** [comment]
Maybe when we open the call for papers for the conference we can put that there?

**Comment by MariusBluem** [comment]
Yap... Nice Idea... But my problem is, that this badge is meant as eye-catcher which should only be used for 2 weeks (more-or-less) if we have important news... normally we should only have this "A safe home for all your data" stuff there - otherwise - as I've said, it will loose its "eyecatcher-function" - but you are our marketing hero 🙈

**Comment by jospoortvliet** [comment]
so how about we close this and link to our security scanner? ;-) will make a PR.

**Pull request closed without merging**
