### PR TITLE
Jobs

### PR DESCRIPTION
**Pull request by jospoortvliet**
Adding 2 jobs: sales engineer and account manager.

jobs nextcloud

### CODE REVIEW

**Comment by Espina2** [comment]
Can I suggest to collapse all the information of the "job" and only show them when toggled?

**Comment by jospoortvliet** [comment]
Yeah... yeah, I can do that.

**Comment by jospoortvliet** [comment]
spectacle j32444

So now it is collapsible and I 'upgraded' to the new style because I had issues with the collapse (somehow bootstrap is loaded twice which breaks collapsible links)

Sadly, the reveal-on-scroll doesn't work when a page is so big you can't scroll :disappointed: 

what do I do about that? just disable it in the footer?

**Comment by Espina2** [comment]
Okey, tomorrow I will take a look with you in this page. Maybe add a nice image on top like the new pages, and some tweak here and here.

**Pull request merged**
