### PR TITLE
add language choice buttons

### PR DESCRIPTION
**Pull request by jospoortvliet**
screenshot_20180420_225916
screenshot_20180420_225856
screenshot_20180420_225945

Can go live as soon as the last 50 strings are reviewed on Transifex & deployed. TODO:
* [ ] about page
* [ ] files page
* [ ] install page
* [ ] Nc Box page

Signed-off-by: Jos Poortvliet <jospoortvliet@gmail.com>

### CODE REVIEW

**Comment by MariusBluem** [comment]
Could we only show the non-selected language as button? (If English - show German, if German - show English)

**Comment by MariusBluem** [comment]
Do we have a flag which covers american and british english with only one button?

Example: https://commons.m.wikimedia.org/wiki/File:English_language.svg

**Comment by jospoortvliet** [comment]
1. how is your PHP? Cuz no, I can't do that.
2. I could put a different flag up, sure, but I think this is good enough... Everyone will understand that these countries speak roughly the same language ;-)

**Comment by MariusBluem** [comment]
1. PHP - what is that???!!! ;) ;)
2. Fine.

Otherwise: 👍

**Pull request merged**
