### PR TITLE
update Home/SME server

### PR DESCRIPTION
**Pull request by enoch85**
@szaimen

### CODE REVIEW

**Comment by szaimen** [comment]
I adjusted it on the website. 

Unfortunately the changes are not longer getting done here but in wp-admin gui since the relaunch...

**Comment by enoch85** [comment]
@szaimen Can you change accordingly? Or who should I ping?

**Comment by szaimen** [comment]
I already adjusted accordingly. Can you confirm?

**Comment by enoch85** [comment]
Hmm, think the link is broken. The link refers to `Devices` while it should be `devices`.

Your changes looks good though! Thanks!

**Pull request closed without merging**
