### PR TITLE
talk about packages for linux

### PR DESCRIPTION
**Pull request by jospoortvliet**
Clarity about linux packages & links

### CODE REVIEW

**Comment by jospoortvliet** [comment]
@jancborchardt

**Comment by MariusBluem** [comment]
Could we provide install instructions for Linux distributions 😁🙈

**Comment by Espina2** [comment]
@MariusBluem install instructions should be in the documention page. Of course in the download page should a have link for the page. 

Did you agree @jospoortvliet ?

**Comment by jospoortvliet** [comment]
The instructions are, of course, distribution-dependent: apt-get install etcetera. In general, I don't think it is our job to provide that, the distributions have all their own ways of installing software and tell their users about it... Plus, they change it all the time. But wherever it should be, it doesn't belong here.

**Comment by jospoortvliet** [comment]
@MariusBluem what do you think about it this way? I merged your changes and these, just saying:
"You can find Nextcloud Desktop client packages included in openSUSE Tumbleweed, Archlinux, Fedora (on Copr). Ask your distribution for packages or contribute!"

**Comment by MariusBluem** [comment]
:+1:

**Pull request merged**
